import { locale } from "../i18n";
// Each row has English and all eight additional atlas locales.
export const communityCopy = [
  ["Community rules", "Normas de la comunidad", "Règles de la communauté", "Community-Regeln", "Regras da comunidade", "Regole della comunità", "社区规则", "コミュニティ規則", "커뮤니티 규칙"],
  ["Terms", "Condiciones", "Conditions", "Bedingungen", "Termos", "Termini", "条款", "利用規約", "이용 약관"],
  ["Privacy", "Privacidad", "Confidentialité", "Datenschutz", "Privacidade", "Privacy", "隐私", "プライバシー", "개인정보"],
  ["Suspend", "Suspender", "Suspendre", "Sperren", "Suspender", "Sospendi", "暂停账户", "アカウントを停止", "계정 정지"],
  ["Restore", "Restaurar", "Rétablir", "Wiederherstellen", "Restaurar", "Ripristina", "恢复", "復元", "복원"],
  ["Cancel votes", "Anular votos", "Annuler les votes", "Stimmen löschen", "Cancelar votos", "Annulla voti", "撤销投票", "投票を取り消す", "투표 취소"],
  ["No photos need review.", "No hay fotos pendientes de revisión.", "Aucune photo à examiner.", "Keine Fotos zur Prüfung.", "Nenhuma foto precisa de revisão.", "Nessuna foto da esaminare.", "没有待审核照片。", "審査待ちの写真はありません。", "검토할 사진이 없습니다."],
  [
    "Image",
    "Imagen",
    "Image",
    "Bild",
    "Imagem",
    "Immagine",
    "图像",
    "画像",
    "이미지",
  ],
  [
    "Title",
    "Título",
    "Titre",
    "Titel",
    "Título",
    "Titolo",
    "标题",
    "タイトル",
    "제목",
  ],
  [
    "Capture time (UTC)",
    "Fecha de captura (UTC)",
    "Date de prise (UTC)",
    "Aufnahmezeit (UTC)",
    "Data da captura (UTC)",
    "Data di ripresa (UTC)",
    "拍摄时间 (UTC)",
    "撮影時刻 (UTC)",
    "촬영 시각 (UTC)",
  ],
  [
    "Caption",
    "Descripción",
    "Description",
    "Beschreibung",
    "Descrição",
    "Descrizione",
    "说明",
    "説明",
    "설명",
  ],
  [
    "Equipment",
    "Equipo",
    "Équipement",
    "Ausrüstung",
    "Equipamento",
    "Attrezzatura",
    "设备",
    "機材",
    "장비",
  ],
  [
    "Processing",
    "Procesado",
    "Traitement",
    "Bearbeitung",
    "Processamento",
    "Elaborazione",
    "处理",
    "処理",
    "처리",
  ],
  [
    "Licence",
    "Licencia",
    "Licence",
    "Lizenz",
    "Licença",
    "Licenza",
    "许可",
    "ライセンス",
    "라이선스",
  ],
  [
    "Reason",
    "Motivo",
    "Motif",
    "Grund",
    "Motivo",
    "Motivo",
    "原因",
    "理由",
    "사유",
  ],
  [
    "Send report",
    "Enviar denuncia",
    "Envoyer le signalement",
    "Meldung senden",
    "Enviar denúncia",
    "Invia segnalazione",
    "发送举报",
    "報告を送信",
    "신고 보내기",
  ],
  [
    "Open object",
    "Abrir objeto",
    "Ouvrir l’objet",
    "Objekt öffnen",
    "Abrir objeto",
    "Apri oggetto",
    "打开天体",
    "天体を開く",
    "천체 열기",
  ],
  [
    "Composite or heavily processed photo",
    "Foto compuesta o muy procesada",
    "Photo composite ou fortement traitée",
    "Zusammengesetztes oder stark bearbeitetes Foto",
    "Foto composta ou muito processada",
    "Foto composita o molto elaborata",
    "合成或深度处理照片",
    "合成または大幅に処理した写真",
    "합성 또는 강하게 처리한 사진",
  ],
  [
    "I own this photo or have permission to publish it. This is not a synthetic AI image.",
    "Soy autor o tengo permiso para publicar esta foto. No es una imagen sintética de IA.",
    "Je suis l’auteur ou j’ai l’autorisation de publier cette photo. Ce n’est pas une image synthétique par IA.",
    "Ich besitze das Foto oder habe die Erlaubnis zur Veröffentlichung. Es ist kein synthetisches KI-Bild.",
    "Sou o autor ou tenho permissão para publicar. Esta não é uma imagem sintética de IA.",
    "Sono l’autore o ho il permesso di pubblicare. Non è un’immagine sintetica generata da IA.",
    "我拥有此照片或获得了发布许可。这不是 AI 生成的合成图像。",
    "この写真の権利または公開許可があります。AI が生成した合成画像ではありません。",
    "사진의 권리가 있거나 게시 허가를 받았습니다. AI로 생성한 합성 이미지가 아닙니다.",
  ],
  [
    "The first three photos need moderator review. Your copyright stays with you.",
    "Las tres primeras fotos requieren revisión. Conservas tus derechos de autor.",
    "Les trois premières photos sont modérées. Vous gardez vos droits d’auteur.",
    "Die ersten drei Fotos werden geprüft. Ihr Urheberrecht bleibt erhalten.",
    "As três primeiras fotos precisam de revisão. Seus direitos autorais permanecem com você.",
    "Le prime tre foto richiedono una revisione. Mantieni il copyright.",
    "前三张照片需要审核。版权仍归您所有。",
    "最初の3枚は審査が必要です。著作権はあなたに残ります。",
    "처음 세 장은 검토가 필요합니다. 저작권은 계속 귀하에게 있습니다.",
  ],
  [
    "Display name",
    "Nombre visible",
    "Nom affiché",
    "Anzeigename",
    "Nome de exibição",
    "Nome visualizzato",
    "显示名称",
    "表示名",
    "표시 이름",
  ],
  [
    "Public handle",
    "Nombre público",
    "Identifiant public",
    "Öffentlicher Name",
    "Identificador público",
    "Nome pubblico",
    "公开用户名",
    "公開ユーザー名",
    "공개 사용자 이름",
  ],
  [
    "Save profile",
    "Guardar perfil",
    "Enregistrer le profil",
    "Profil speichern",
    "Salvar perfil",
    "Salva profilo",
    "保存资料",
    "プロフィールを保存",
    "프로필 저장",
  ],
  [
    "My photos",
    "Mis fotos",
    "Mes photos",
    "Meine Fotos",
    "Minhas fotos",
    "Le mie foto",
    "我的照片",
    "自分の写真",
    "내 사진",
  ],
  [
    "Remove",
    "Retirar",
    "Retirer",
    "Entfernen",
    "Remover",
    "Rimuovi",
    "移除",
    "削除",
    "삭제",
  ],
  [
    "Sky coordinates",
    "Coordenadas celestes",
    "Coordonnées célestes",
    "Himmelskoordinaten",
    "Coordenadas celestes",
    "Coordinate celesti",
    "天球坐标",
    "天球座標",
    "천구 좌표",
  ],
  [
    "Solve field",
    "Resolver campo",
    "Résoudre le champ",
    "Sternfeld lösen",
    "Resolver campo",
    "Risolvi campo",
    "解析星场",
    "星野を解析",
    "별 영역 분석",
  ],
  [
    "Export account data",
    "Exportar datos de la cuenta",
    "Exporter les données du compte",
    "Kontodaten exportieren",
    "Exportar dados da conta",
    "Esporta dati dell’account",
    "导出账户数据",
    "アカウントデータを書き出す",
    "계정 데이터 내보내기",
  ],
  [
    "Remove account",
    "Eliminar cuenta",
    "Supprimer le compte",
    "Konto löschen",
    "Excluir conta",
    "Elimina account",
    "删除账户",
    "アカウントを削除",
    "계정 삭제",
  ],
  [
    "Sign out",
    "Cerrar sesión",
    "Déconnexion",
    "Abmelden",
    "Sair",
    "Esci",
    "退出登录",
    "ログアウト",
    "로그아웃",
  ],
  [
    "Remove my account",
    "Eliminar mi cuenta",
    "Supprimer mon compte",
    "Mein Konto löschen",
    "Excluir minha conta",
    "Elimina il mio account",
    "删除我的账户",
    "自分のアカウントを削除",
    "내 계정 삭제",
  ],
  [
    "This removes your account and hides all your photos. This action cannot be undone.",
    "Se eliminará tu cuenta y se ocultarán todas tus fotos. No se puede deshacer.",
    "Votre compte sera supprimé et vos photos masquées. Cette action est définitive.",
    "Ihr Konto wird gelöscht und alle Fotos werden verborgen. Dies lässt sich nicht rückgängig machen.",
    "Sua conta será excluída e suas fotos ocultadas. Esta ação não pode ser desfeita.",
    "L’account sarà eliminato e tutte le foto nascoste. L’azione è irreversibile.",
    "这将删除您的账户并隐藏全部照片。此操作无法撤销。",
    "アカウントを削除し、すべての写真を非公開にします。元に戻せません。",
    "계정을 삭제하고 모든 사진을 숨깁니다. 취소할 수 없습니다.",
  ],
  [
    "Profile saved.",
    "Perfil guardado.",
    "Profil enregistré.",
    "Profil gespeichert.",
    "Perfil salvo.",
    "Profilo salvato.",
    "资料已保存。",
    "プロフィールを保存しました。",
    "프로필을 저장했습니다.",
  ],
  [
    "Plate solve queued.",
    "Resolución en cola.",
    "Résolution mise en attente.",
    "Sternfeldanalyse eingereiht.",
    "Resolução na fila.",
    "Risoluzione in coda.",
    "星场解析已加入队列。",
    "星野解析を予約しました。",
    "별 영역 분석을 대기열에 추가했습니다.",
  ],
  [
    "Save coordinates",
    "Guardar coordenadas",
    "Enregistrer les coordonnées",
    "Koordinaten speichern",
    "Salvar coordenadas",
    "Salva coordinate",
    "保存坐标",
    "座標を保存",
    "좌표 저장",
  ],
  [
    "Use a square-pixel TAN solution. These coordinates will be labelled as supplied by the author.",
    "Usa una solución TAN con píxeles cuadrados. Se indicará que el autor proporcionó estas coordenadas.",
    "Utilisez une solution TAN à pixels carrés. Les coordonnées seront indiquées comme fournies par l’auteur.",
    "Verwenden Sie eine TAN-Lösung mit quadratischen Pixeln. Die Koordinaten werden als Angaben des Autors gekennzeichnet.",
    "Use uma solução TAN com pixels quadrados. As coordenadas serão identificadas como fornecidas pelo autor.",
    "Usa una soluzione TAN con pixel quadrati. Le coordinate saranno indicate come fornite dall’autore.",
    "请使用方形像素的 TAN 解算。坐标将标注为作者提供。",
    "正方形ピクセルの TAN 解を使用してください。座標は撮影者の入力として表示します。",
    "정사각형 픽셀의 TAN 해를 사용하세요. 좌표는 작성자가 제공한 것으로 표시됩니다.",
  ],
  [
    "Photo opacity",
    "Opacidad de la foto",
    "Opacité de la photo",
    "Foto-Deckkraft",
    "Opacidade da foto",
    "Opacità della foto",
    "照片不透明度",
    "写真の不透明度",
    "사진 불투명도",
  ],
  [
    "All time",
    "Siempre",
    "Toutes dates",
    "Gesamter Zeitraum",
    "Todo o período",
    "Tutte le date",
    "全部时间",
    "全期間",
    "전체 기간",
  ],
  [
    "Trending",
    "Tendencias",
    "Tendances",
    "Aktuell beliebt",
    "Em alta",
    "Di tendenza",
    "热门",
    "トレンド",
    "인기",
  ],
  [
    "Approve",
    "Aprobar",
    "Approuver",
    "Freigeben",
    "Aprovar",
    "Approva",
    "批准",
    "承認",
    "승인",
  ],
  [
    "Reject",
    "Rechazar",
    "Refuser",
    "Ablehnen",
    "Rejeitar",
    "Rifiuta",
    "拒绝",
    "却下",
    "거부",
  ],
  [
    "Hide",
    "Ocultar",
    "Masquer",
    "Verbergen",
    "Ocultar",
    "Nascondi",
    "隐藏",
    "非公開",
    "숨기기",
  ],
  [
    "Restore",
    "Restaurar",
    "Rétablir",
    "Wiederherstellen",
    "Restaurar",
    "Ripristina",
    "恢复",
    "復元",
    "복구",
  ],
  [
    "No photos need review.",
    "No hay fotos pendientes.",
    "Aucune photo à examiner.",
    "Keine Fotos zu prüfen.",
    "Nenhuma foto para revisar.",
    "Nessuna foto da esaminare.",
    "没有待审核照片。",
    "審査待ちの写真はありません。",
    "검토할 사진이 없습니다.",
  ],
  [
    "Preparing upload…",
    "Preparando subida…",
    "Préparation de l’envoi…",
    "Upload wird vorbereitet…",
    "Preparando envio…",
    "Preparazione del caricamento…",
    "正在准备上传…",
    "アップロードを準備中…",
    "업로드 준비 중…",
  ],
  [
    "Uploading…",
    "Subiendo…",
    "Envoi…",
    "Wird hochgeladen…",
    "Enviando…",
    "Caricamento…",
    "正在上传…",
    "アップロード中…",
    "업로드 중…",
  ],
  [
    "Upload received.",
    "Subida recibida.",
    "Envoi reçu.",
    "Upload empfangen.",
    "Envio recebido.",
    "Caricamento ricevuto.",
    "已收到上传。",
    "アップロードを受信しました。",
    "업로드를 받았습니다.",
  ],
  [
    "Your photo is processing. Check its status in your account.",
    "Se está procesando tu foto. Consulta su estado en tu cuenta.",
    "Votre photo est en cours de traitement. Consultez son état dans votre compte.",
    "Ihr Foto wird verarbeitet. Prüfen Sie den Status in Ihrem Konto.",
    "Sua foto está sendo processada. Verifique o status na sua conta.",
    "La foto è in elaborazione. Controlla lo stato nel tuo account.",
    "照片正在处理。请在账户中查看状态。",
    "写真を処理中です。アカウントで状態を確認してください。",
    "사진을 처리 중입니다. 계정에서 상태를 확인하세요.",
  ],
  [
    "Use a file smaller than 60 MB.",
    "Usa un archivo de menos de 60 MB.",
    "Utilisez un fichier de moins de 60 Mo.",
    "Verwenden Sie eine Datei unter 60 MB.",
    "Use um arquivo menor que 60 MB.",
    "Usa un file inferiore a 60 MB.",
    "请使用小于 60 MB 的文件。",
    "60 MB 未満のファイルを使用してください。",
    "60 MB보다 작은 파일을 사용하세요.",
  ],
  [
    "Upload failed. Please try again.",
    "La subida falló. Inténtalo de nuevo.",
    "Échec de l’envoi. Réessayez.",
    "Upload fehlgeschlagen. Versuchen Sie es erneut.",
    "O envio falhou. Tente novamente.",
    "Caricamento fallito. Riprova.",
    "上传失败。请重试。",
    "アップロードに失敗しました。再試行してください。",
    "업로드에 실패했습니다. 다시 시도하세요.",
  ],
  [
    "Photo, view from Earth",
    "Foto, vista desde la Tierra",
    "Photo, vue depuis la Terre",
    "Foto, Blick von der Erde",
    "Foto, vista da Terra",
    "Foto, vista dalla Terra",
    "照片，从地球观测",
    "写真、地球からの眺め",
    "사진, 지구에서 본 모습",
  ],
  [
    "Plate-solved footprint",
    "Huella resuelta",
    "Empreinte astrométrique",
    "Astrometrisch gelöster Bildrahmen",
    "Área resolvida",
    "Impronta risolta",
    "解析后的覆盖范围",
    "解析済みの撮影範囲",
    "분석된 촬영 영역",
  ],
  [
    "Author-supplied footprint",
    "Huella proporcionada por el autor",
    "Empreinte fournie par l’auteur",
    "Bildrahmen nach Autorenangaben",
    "Área fornecida pelo autor",
    "Impronta fornita dall’autore",
    "作者提供的覆盖范围",
    "撮影者が入力した撮影範囲",
    "작성자가 제공한 촬영 영역",
  ],
  [
    "Coverage",
    "Cobertura",
    "Couverture",
    "Abdeckung",
    "Cobertura",
    "Copertura",
    "覆盖率",
    "撮影対象",
    "촬영 범위",
  ],
  [
    "Photographers",
    "Fotógrafos",
    "Photographes",
    "Fotografen",
    "Fotógrafos",
    "Fotografi",
    "摄影师",
    "撮影者",
    "사진가",
  ],
  [
    "Load more",
    "Cargar más",
    "Charger plus",
    "Mehr laden",
    "Carregar mais",
    "Carica altro",
    "加载更多",
    "さらに読み込む",
    "더 불러오기",
  ],
  [
    "No photo yet",
    "Sin foto",
    "Pas encore de photo",
    "Noch kein Foto",
    "Ainda sem foto",
    "Ancora nessuna foto",
    "暂无照片",
    "写真なし",
    "아직 사진 없음",
  ],
  [
    "Compare survey",
    "Comparar sondeo",
    "Comparer au relevé",
    "Mit Himmelsaufnahme vergleichen",
    "Comparar levantamento",
    "Confronta rilevamento",
    "对比巡天图像",
    "サーベイと比較",
    "서베이 비교",
  ],
  [
    "Archival field. Orientation can differ.",
    "Campo de archivo. La orientación puede ser distinta.",
    "Champ d’archive. L’orientation peut différer.",
    "Archivaufnahme. Die Ausrichtung kann abweichen.",
    "Campo de arquivo. A orientação pode ser diferente.",
    "Campo d’archivio. L’orientamento può differire.",
    "历史星场图像。方向可能不同。",
    "アーカイブの星野です。向きが異なる場合があります。",
    "기록된 별 영역입니다. 방향이 다를 수 있습니다.",
  ],
  [
    "Request failed. Please try again.",
    "La solicitud falló. Inténtalo de nuevo.",
    "La demande a échoué. Réessayez.",
    "Anfrage fehlgeschlagen. Versuchen Sie es erneut.",
    "A solicitação falhou. Tente novamente.",
    "Richiesta fallita. Riprova.",
    "请求失败。请重试。",
    "処理に失敗しました。再試行してください。",
    "요청에 실패했습니다. 다시 시도하세요.",
  ],
  [
    "Please sign in first.",
    "Inicia sesión primero.",
    "Connectez-vous d’abord.",
    "Melden Sie sich zuerst an.",
    "Entre primeiro.",
    "Accedi prima.",
    "请先登录。",
    "先にログインしてください。",
    "먼저 로그인하세요.",
  ],
  [
    "The code is incorrect or expired.",
    "El código es incorrecto o ha caducado.",
    "Le code est incorrect ou expiré.",
    "Der Code ist falsch oder abgelaufen.",
    "O código está incorreto ou expirou.",
    "Il codice è errato o scaduto.",
    "验证码错误或已过期。",
    "コードが違うか期限切れです。",
    "코드가 틀리거나 만료되었습니다.",
  ],
  [
    "You can vote 24 hours after creating your account.",
    "Puedes votar 24 horas después de crear tu cuenta.",
    "Vous pouvez voter 24 heures après la création du compte.",
    "Sie können 24 Stunden nach der Kontoerstellung abstimmen.",
    "Você pode votar 24 horas após criar sua conta.",
    "Puoi votare 24 ore dopo la creazione dell’account.",
    "创建账户 24 小时后即可投票。",
    "アカウント作成の24時間後から投票できます。",
    "계정을 만든 후 24시간이 지나면 투표할 수 있습니다.",
  ],
  [
    "You cannot vote on this photo.",
    "No puedes votar esta foto.",
    "Vous ne pouvez pas voter pour cette photo.",
    "Sie können für dieses Foto nicht abstimmen.",
    "Você não pode votar nesta foto.",
    "Non puoi votare questa foto.",
    "您无法对此照片投票。",
    "この写真には投票できません。",
    "이 사진에 투표할 수 없습니다.",
  ],
  [
    "The plate solver is not configured for this site.",
    "Este sitio no tiene configurado el solucionador.",
    "Le solveur n’est pas configuré sur ce site.",
    "Die Sternfeldanalyse ist für diese Website nicht eingerichtet.",
    "O solucionador não está configurado neste site.",
    "Il risolutore non è configurato per questo sito.",
    "此站点尚未配置星场解析器。",
    "このサイトの星野解析は未設定です。",
    "이 사이트에 별 영역 분석기가 설정되지 않았습니다.",
  ],
  [
    "Email delivery is unavailable. Please try again later.",
    "El correo no está disponible. Inténtalo más tarde.",
    "L’envoi d’e-mails est indisponible. Réessayez plus tard.",
    "E-Mail-Versand ist nicht verfügbar. Versuchen Sie es später.",
    "O envio de e-mail está indisponível. Tente mais tarde.",
    "L’invio di e-mail non è disponibile. Riprova più tardi.",
    "邮件服务暂不可用。请稍后重试。",
    "メールを送信できません。後でもう一度お試しください。",
    "이메일을 보낼 수 없습니다. 나중에 다시 시도하세요.",
  ],
  [
    "Check the photo details and confirm your rights to publish.",
    "Revisa los datos y confirma los derechos de publicación.",
    "Vérifiez les détails et vos droits de publication.",
    "Prüfen Sie die Fotodaten und bestätigen Sie Ihre Veröffentlichungsrechte.",
    "Verifique os dados e confirme os direitos de publicação.",
    "Controlla i dettagli e conferma i diritti di pubblicazione.",
    "请检查照片信息并确认发布权利。",
    "写真の情報と公開権限を確認してください。",
    "사진 정보를 확인하고 게시 권한을 확인하세요.",
  ],
  [
    "You reached the limit of 20 uploads per day.",
    "Alcanzaste el límite de 20 fotos al día.",
    "Vous avez atteint la limite de 20 envois par jour.",
    "Sie haben das Limit von 20 Uploads pro Tag erreicht.",
    "Você atingiu o limite de 20 envios por dia.",
    "Hai raggiunto il limite di 20 caricamenti al giorno.",
    "已达到每天 20 次上传的限制。",
    "1日20回のアップロード上限に達しました。",
    "하루 20회 업로드 한도에 도달했습니다.",
  ],
  [
    "Wait for image processing to finish.",
    "Espera a que termine el procesado.",
    "Attendez la fin du traitement.",
    "Warten Sie, bis die Bildverarbeitung beendet ist.",
    "Aguarde o processamento terminar.",
    "Attendi il termine dell’elaborazione.",
    "请等待图像处理完成。",
    "画像処理の完了をお待ちください。",
    "이미지 처리가 끝날 때까지 기다리세요.",
  ],
  [
    "Use valid square-pixel TAN sky coordinates.",
    "Usa coordenadas TAN válidas con píxeles cuadrados.",
    "Utilisez des coordonnées TAN valides à pixels carrés.",
    "Verwenden Sie gültige TAN-Koordinaten mit quadratischen Pixeln.",
    "Use coordenadas TAN válidas com pixels quadrados.",
    "Usa coordinate TAN valide con pixel quadrati.",
    "请使用有效的方形像素 TAN 天球坐标。",
    "正方形ピクセルの有効な TAN 座標を使用してください。",
    "유효한 정사각형 픽셀 TAN 천구 좌표를 사용하세요.",
  ],
] as const;
const columns = ["en", "es", "fr", "de", "pt-BR", "it", "zh-Hans", "ja", "ko"];
export function cx(text: string): string {
  const row = communityCopy.find((row) => row[0] === text);
  return row?.[columns.indexOf(locale())] ?? text;
}
/** Translate only literal template segments, before user strings are inserted. */
export function communityHtml(
  parts: TemplateStringsArray,
  ...values: unknown[]
): string {
  return parts
    .map(
      (part, i) =>
        part.replace(/>([^<>]+)(?=<)/g, (whole, text) => `>${cx(text)}`) +
        (i < values.length ? String(values[i]) : ""),
    )
    .join("");
}
