export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "The Sun anchors every Solar System orbit in the atlas and provides the reference scale for stellar mass, radius, and luminosity.",
  mercury: "Mercury is the innermost planet, showing how solar heating and tidal history shape small rocky worlds.",
  venus: "Venus is Earth's near twin in size but a climate extreme, making it a key comparison point for terrestrial planet evolution.",
  earth: "Earth is the observing baseline for the atlas and the only known inhabited world, tying sky position to local distance and scale.",
  moon: "The Moon preserves impact and volcanic history close enough to connect telescopic detail with spacecraft-era geology.",
  mars: "Mars is the best-studied nearby rocky planet beyond Earth and a reference for climate loss, volcanism, and surface exploration.",
  jupiter: "Jupiter dominates Solar System dynamics and its major moons form a compact comparison set of geologically diverse worlds.",
  saturn: "Saturn connects giant-planet structure, rings, and moon systems in one of the clearest natural laboratories in the Solar System.",
  uranus: "Uranus is an ice giant with an extreme axial tilt, useful for comparing outer-planet interiors and seasonal geometry.",
  neptune: "Neptune anchors the outer classical planets and shows how fast atmospheric dynamics persist far from the Sun.",
  pluto: "Pluto links dwarf planets, Kuiper Belt history, and volatile geology at the edge of the planetary system.",
  io: "Io is the Solar System's most volcanically active moon, driven by tidal heating inside Jupiter's moon system.",
  europa: "Europa is a high-value ocean-world target because its icy surface likely overlies a global salty ocean.",
  ganymede: "Ganymede is the largest moon in the Solar System and the only moon known to generate its own magnetic field.",
  callisto: "Callisto records ancient outer Solar System impacts and contrasts strongly with the more active inner Galilean moons.",
  titan: "Titan is the only moon with a dense atmosphere and stable surface liquids, making it central to comparative planetary chemistry.",
  enceladus: "Enceladus vents material from a subsurface ocean into space, making it one of the most direct ocean-world sampling targets.",
  m13: "M13 is a benchmark northern globular cluster, showing a dense ancient stellar population in the Milky Way halo.",
  m31: "Andromeda is the nearest large spiral galaxy, placing the Milky Way in direct Local Group context.",
  m42: "The Orion Nebula is a nearby massive star-forming region where young stars illuminate their natal gas and dust.",
  m45: "The Pleiades are a nearby young open cluster, useful for reading stellar color, age, and reflection nebulosity.",
  m57: "The Ring Nebula shows a late Sun-like stellar evolutionary phase, with expelled gas surrounding a hot central remnant.",
};
