defmodule StarsmapApiWeb.Endpoint do
  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :starsmap_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_starsmap_api_key",
    signing_salt: "k6uONTOW",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Versioned catalog point tiles are immutable; serve any locally-present tiles
  # with long-lived headers before the general handler. The versionless manifest
  # must never be reused across a catalog rollover.
  plug Plug.Static,
    at: "/catalog-tiles",
    from: {:starsmap_api, "priv/static/catalog-tiles"},
    gzip: not code_reloading?,
    headers: {__MODULE__, :catalog_tile_cache_headers, []}

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :starsmap_api,
    gzip: not code_reloading?,
    only: StarsmapApiWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :starsmap_api
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Sentry.PlugContext
  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug StarsmapApiWeb.Router

  @doc false
  def catalog_tile_cache_headers(conn) do
    cache_control =
      if String.ends_with?(conn.request_path, ".bin") do
        "public, max-age=31536000, immutable"
      else
        "no-store"
      end

    %{"cache-control" => cache_control}
  end
end
