function requiredElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) throw new Error(`Missing required element: ${selector}`);
  return element;
}

const canvas = requiredElement<HTMLCanvasElement>("#map");
const context = canvas.getContext("2d");
if (!context) throw new Error("Canvas 2D context is not available");

/** The validated DOM interface consumed by the atlas runtime. */
export const atlasDom = {
  pointCanvas: requiredElement<HTMLCanvasElement>("#point-map"),
  canvas,
  ctx: context,
  catalogPointHover: requiredElement<HTMLElement>("#catalog-point-hover"),
  selectionConnector: requiredElement<SVGSVGElement>("#selection-connector"),
  loadingScreen: requiredElement<HTMLElement>("#loading-screen"),
  loadingDetail: requiredElement<HTMLElement>("#loading-detail"),
  loadingFill: requiredElement<HTMLElement>("#loading-progress-fill"),
  loadingProgressLabel: requiredElement<HTMLElement>("#loading-progress-label"),
  loadingStepLabel: requiredElement<HTMLElement>("#loading-step-label"),
  loadingElapsed: requiredElement<HTMLElement>("#loading-elapsed"),
  loadState: requiredElement<HTMLElement>("#load-state"),
  atlasStats: requiredElement<HTMLElement>("#atlas-stats"),
  selectedObjectPanel: requiredElement<HTMLElement>("#selected-object-panel"),
  selectedSummaryOrb: requiredElement<HTMLElement>("#selected-summary-orb"),
  selectedSummaryName: requiredElement<HTMLElement>("#selected-summary-name"),
  selectedSummaryMeta: requiredElement<HTMLElement>("#selected-summary-meta"),
  mapHud: requiredElement<HTMLElement>("#controls"),
  workspacePanel: requiredElement<HTMLElement>("#workspace-panel"),
  workspaceLabel: requiredElement<HTMLElement>("#workspace-label"),
  workspaceSearchLink: requiredElement<HTMLButtonElement>("#workspace-search-link"),
  closePanel: requiredElement<HTMLButtonElement>("#close-panel"),
  modeRail: requiredElement<HTMLElement>(".mode-rail"),
  bodySearch: requiredElement<HTMLInputElement>("#body-search"),
  focusBodyButton: requiredElement<HTMLButtonElement>("#focus-body"),
  quickFocusButtons: requiredElement<HTMLElement>("#quick-focus-buttons"),
  tabButtons: Array.from(document.querySelectorAll<HTMLButtonElement>("[data-tab]")),
  tabPanels: Array.from(document.querySelectorAll<HTMLElement>("[data-tab-panel]")),
  catalogCount: requiredElement<HTMLElement>("#catalog-count"),
  bodyFilterButtons: requiredElement<HTMLElement>("#body-filter-buttons"),
  mapFilterButtons: requiredElement<HTMLElement>("#map-filter-buttons"),
  bodyPicker: requiredElement<HTMLElement>("#body-picker"),
  exploreDomains: requiredElement<HTMLElement>("#explore-domains"),
  guidedTours: requiredElement<HTMLElement>("#guided-tours"),
  bodyInfo: requiredElement<HTMLElement>("#body-info"),
  selectionCompare: requiredElement<HTMLElement>("#selection-compare"),
  compareSelected: requiredElement<HTMLButtonElement>("#compare-selected"),
  nowStatus: requiredElement<HTMLElement>("#now-status"),
  nowEvents: requiredElement<HTMLOListElement>("#now-events"),
  centerSelected: requiredElement<HTMLButtonElement>("#center-selected"),
  zoomSelected: requiredElement<HTMLButtonElement>("#zoom-selected"),
  viewSkySelected: requiredElement<HTMLButtonElement>("#view-sky-selected"),
  skyView: requiredElement<HTMLElement>("#sky-view"),
  skyCanvas: requiredElement<HTMLCanvasElement>("#sky-map"),
  skyTitle: requiredElement<HTMLElement>("#sky-view-title"),
  skyMeta: requiredElement<HTMLElement>("#sky-view-meta"),
  skyStatus: requiredElement<HTMLElement>("#sky-view-status"),
  skyTooltip: requiredElement<HTMLElement>("#sky-view-tooltip"),
  skyClose: requiredElement<HTMLButtonElement>("#sky-view-close"),
  skyReset: requiredElement<HTMLButtonElement>("#sky-view-reset"),
  skyTimeBack: requiredElement<HTMLButtonElement>("#sky-time-back"),
  skyTimeForward: requiredElement<HTMLButtonElement>("#sky-time-forward"),
  compareHeading: requiredElement<HTMLElement>("#compare-heading"),
  clearCompare: requiredElement<HTMLButtonElement>("#clear-compare"),
  compareSearch: requiredElement<HTMLInputElement>("#compare-search"),
  compareFocus: requiredElement<HTMLButtonElement>("#compare-focus"),
  compareFilterButtons: requiredElement<HTMLElement>("#compare-filter-buttons"),
  comparePicker: requiredElement<HTMLElement>("#compare-picker"),
  comparePanel: requiredElement<HTMLElement>("#compare-panel"),
  timeSummary: requiredElement<HTMLElement>("#time-summary"),
  timeInput: requiredElement<HTMLInputElement>("#time-input"),
  timeNow: requiredElement<HTMLButtonElement>("#time-now"),
  applyTime: requiredElement<HTMLButtonElement>("#apply-time"),
  timeStepLabel: requiredElement<HTMLElement>("#time-step-label"),
  timeStepSlider: requiredElement<HTMLInputElement>("#time-step-slider"),
  timeStepBack: requiredElement<HTMLButtonElement>("#time-step-back"),
  timeStepForward: requiredElement<HTMLButtonElement>("#time-step-forward"),
  timeBusy: requiredElement<HTMLElement>("#time-busy"),
  zoomPresets: requiredElement<HTMLElement>("#zoom-presets"),
  mobileScaleToggle: document.querySelector<HTMLButtonElement>("#mobile-scale-toggle"),
  zoomOut: requiredElement<HTMLButtonElement>("#zoom-out"),
  zoomIn: requiredElement<HTMLButtonElement>("#zoom-in"),
  zoomScaleSlider: requiredElement<HTMLInputElement>("#zoom-scale-slider"),
  zoomScaleLabel: requiredElement<HTMLOutputElement>("#zoom-scale-label"),
  zoomPixelScale: requiredElement<HTMLElement>("#zoom-pixel-scale"),
  zoomViewScale: requiredElement<HTMLElement>("#zoom-view-scale"),
  sizeModeButtons: requiredElement<HTMLElement>("#size-mode-buttons"),
  displayToggles: requiredElement<HTMLElement>("#display-toggles"),
  diagnosticsToggle: requiredElement<HTMLInputElement>("#diagnostics-toggle"),
  contextModeStatus: requiredElement<HTMLElement>("#context-mode-status"),
  scienceLayerDisclosure: requiredElement<HTMLElement>("#science-layer-disclosure"),
  perfHud: document.querySelector<HTMLElement>("#perf-hud"),
  errorPanel: requiredElement<HTMLElement>("#error-panel"),
  exportResolution: requiredElement<HTMLSelectElement>("#export-resolution"),
  exportButton: requiredElement<HTMLButtonElement>("#export-image"),
  exportStatus: requiredElement<HTMLElement>("#export-status"),
  copyLinkButton: requiredElement<HTMLButtonElement>("#copy-link"),
  nativeShareButton: requiredElement<HTMLButtonElement>("#native-share"),
  shareFeedback: requiredElement<HTMLElement>("#share-feedback"),
  shareCompareButton: requiredElement<HTMLButtonElement>("#share-compare"),
  copyEmbedButton: requiredElement<HTMLButtonElement>("#copy-embed"),
  embedFeedback: requiredElement<HTMLElement>("#embed-feedback"),
  shareMenuButton: requiredElement<HTMLButtonElement>("#share-menu-button"),
  sharePopover: requiredElement<HTMLElement>("#share-popover"),
  closeSharePopoverButton: requiredElement<HTMLButtonElement>("#close-share-popover"),
  controlInfoTooltip: requiredElement<HTMLElement>("#control-info-tooltip"),
  embedActivation: requiredElement<HTMLButtonElement>("#embed-activation"),
  embedAttribution: requiredElement<HTMLElement>("#embed-attribution"),
  embedCanonicalLink: requiredElement<HTMLAnchorElement>("#embed-canonical-link"),
  embedViewName: requiredElement<HTMLElement>("#embed-view-name"),
};
