#!/usr/bin/env python3
"""Refresh measured partial progress; never infer a complete serving total."""
import json
from pathlib import Path
import os

ROOT=Path(__file__).resolve().parents[1]
WORK=ROOT/'data/storage-exhaustive-1271'
LEDGER=ROOT/'data/catalog-registry/exhaustive-storage-ledger.json'


def read(path):return json.loads(path.read_text())


def progress_table(ledger):
    """One row per inventory entry; partial measurements never become totals."""
    lines=['# Measured catalog storage progress', '',
           '**INCOMPLETE.** Generated by `python3 scripts/report_exhaustive_storage_progress.py`.', '',
           'All sizes below are measured logical bytes, not estimates. “Unknown” is not zero.',
           'Complete-file sums may include supporting tables and documentation. They do not establish full-release coverage.',
           'Rows in observations, notes and crossmatches must not be summed as unique objects.',
           'The JSON ledger retains allocated bytes, checksums and individual file evidence.', '',
           '| Catalog | Measured source evidence | Full-schema detail | Built lookup component | Complete serving total |',
           '|---|---|---|---|---|']
    ids=set()
    for entry in ledger['catalogs']:
        key=entry['id']
        if key in ids:raise ValueError('duplicate inventory entry')
        ids.add(key)
        artifacts=entry['artifacts']; source=artifacts['complete_source']
        evidence=entry.get('acquired_file_set',{})
        src=(f"{source['logical_bytes']:,} ({source['status']})" if source.get('logical_bytes') is not None else
             f"{evidence['source_bytes']:,} across {evidence['files']} complete files; release coverage pending" if evidence else 'Unknown')
        detail=artifacts['full_schema_detail'].get('logical_bytes')
        detail=f'{detail:,}' if detail is not None else 'Unknown'
        lookup=artifacts['id_routing'].get('logical_bytes')
        lookup=f'{lookup:,} (combined component; see ledger)' if lookup is not None else 'Unbuilt/unmeasured'
        if key=='gaia-dr3':
            r=ledger['active_run']['progress_at_checkpoint']
            src=f"{r['measured_source_bytes_for_verified_files']:,}; {r['verified_files']}/3386 files, {r['verified_rows']:,} rows"
            detail=f"{r['measured_detail_bytes_for_verified_files']:,} (partial release)"
            route=ledger.get('gaia_partial_id_routing')
            if route:lookup=f"{route['logical_bytes']:,}; {route['measured_files']}/3386 files"
        if key=='2mass-psc' and 'psc_full_run_progress' in ledger:
            r=ledger['psc_full_run_progress']
            src=f"{r['files']}/92 files, {r['rows']:,} rows; source bytes in file receipts"
            detail=f"{r['measured_detail_bytes']:,} (partial release)"
            complete=ledger.get('psc_completion_audit')
            if complete:
                src=f"{complete['source_bytes']:,}; all 92 files, {complete['rows']:,} rows"
                detail=f"{complete['candidate_data_bytes']:,} (complete 60-field candidate; serving incomplete)"
            trial=ledger.get('psc_index_trial_measurement')
            if trial:lookup=f"{trial['logical_bytes']:,}; {trial['files']}/92 files (trial)"
            running=ledger.get('psc_global_index_progress')
            if running:lookup=f"{running['logical_bytes']:,}; {running['committed_files']}/92 committed files (global build in progress)"
        if key=='small-bodies' and 'sbdb_category_measurements' in ledger:
            r=ledger['sbdb_category_measurements']
            src=f"{r['measured_category_source_bytes']:,}; all four category exports, atomic snapshot unproven"
            stored=ledger.get('sbdb_owned_measurement')
            if stored:
                detail=f"{stored['detail_bytes']:,} (all category records)"
                lookup=f"{stored['index_bytes']:,} (ID/name/routing component)"
        if key=='blazars' and 'bzcat_candidate_measurement' in ledger:
            r=ledger['bzcat_candidate_measurement']
            src=f"{r['source']['bytes']:,} (complete BZCAT5 candidate; original compilation scope unresolved)"
            detail=f"{r['data']['bytes']:,} (candidate only)"
            lookup=f"{r['lookup']['bytes']:,} (candidate exact lookup only)"
        if key=='sdss' and 'sdss_run_listing_verification' in ledger:
            r=ledger['sdss_run_listing_verification']['groups']['photoObj']
            src=f"Unknown; provider lists {r['provider_reported_bytes']:,} bytes in {r['files']:,} PhotoObj files"
        if key=='allwise' and 'allwise_measured_progress' in ledger:
            r=ledger['allwise_measured_progress']
            src=f"{r['source_bytes']:,}; {r['files']}/12288 files, {r['rows']:,} rows"
            detail=f"{r['candidate_detail_bytes']:,} (partial candidate layout)"
            trial=ledger.get('allwise_lookup_trial')
            if trial:lookup=f"{trial['logical_bytes']:,}; {trial['files']}/12288 files (ID/name trial)"
        if key=='openngc' and 'openngc_evidence_index' in ledger:
            r=ledger['openngc_evidence_index']
            lookup+=f"; {r['bytes']:,} additional published-name/angular component"
        lines.append(f'| {key} | {src} | {detail} | {lookup} | Unknown |')
    lines += ['', 'No exhaustive source, serving, build-workspace or rollback total has yet been established.',
              'Build projections are temporary inputs, not serving indexes. Runtime estimates and observed scratch peaks remain in the ledger.', '']
    return '\n'.join(lines)


def main():
    ledger=read(LEDGER)
    receipts=[read(p) for p in sorted((WORK/'gaia-full/receipts').glob('*.json'))]
    measured={'status':'INCOMPLETE','verified_files':len(receipts),'expected_files':3386,
              'verified_rows':sum(r['rows'] for r in receipts),
              'measured_source_bytes_for_verified_files':sum(r['source_bytes'] for r in receipts),
              'measured_detail_bytes_for_verified_files':sum(r['parquet_bytes'] for r in receipts),
              'complete_serving_bytes':None,'source_schema_columns':152,
              'retained_build_projection_files':sum('build_projection' in r for r in receipts),
              'retained_build_projection_bytes':sum(r.get('build_projection',{}).get('bytes',0) for r in receipts)}
    ledger['active_run']['progress_at_checkpoint']=measured
    ledger['active_run']['runtime_estimate_hours']=[70,80]
    ledger['active_run']['build_projection_precision']='Original ECSV declared types; full detail still preserves decimal-to-f64 source values'
    for key,path in {
        'gaia_partial_id_routing':'gaia-full/id-routing.receipt.json',
        'gaia_routing_projection_verification_progress':'gaia-full/routing-projection-verification-progress.json',
        'gaia_routing_projection_verification':'gaia-full/routing-projection-verification.json',
        'psc_provider_file_metadata':'acquisition/psc-complete-file-inventory.json',
        'psc_first_source_download':'acquisition/psc-first-source-download.json',
        'workspace_observed_peak':'workspace-observed-peak.json',
        'psc_full_run_progress':'psc-full/progress.json',
        'psc_completion_audit':'psc-full/completion-audit.json',
        'psc_first_complete_file_measurement':'psc-full/receipts/psc_aaa.gz.json',
        'survey_fits_provider_metadata':'acquisition/survey-fits-heads.json',
        'erosita_main_source_progress':'erosita-main-source/progress.json',
        'erosita_main_source_bytes':'erosita-main-source/receipt.json',
        'erosita_main_source_audit':'erosita-main-source/fits-audit.json',
        'erosita_main_source_pin':'erosita-main-source/manifest.json',
        'erosita_main_owned_progress':'erosita-main-owned-evidence/progress.json',
        'erosita_main_owned_measurement':'erosita-main-owned-evidence/measurement.json',
        'hipparcos_full_field_audit':'small-releases/hipparcos-fields-receipt.json',
        'additional_batch_component_reconciliation':'additional-components-reconciliation.json',
        'hipparcos_owned_progress':'hipparcos-owned-evidence/progress.json',
        'hipparcos_owned_measurement':'hipparcos-owned-evidence/measurement.json',
        'hipparcos_exact_lookup':'hipparcos-owned-evidence/exact-lookup.json',
        'hipparcos_exact_lookup_progress':'hipparcos-owned-evidence/exact-lookup-progress.json',
        'erosita_main_exact_lookup':'erosita-main-owned-evidence/exact-lookup.json',
        'erosita_main_exact_lookup_progress':'erosita-main-owned-evidence/exact-lookup-progress.json',
        'erosita_ls10_source_progress':'erosita-ls10-source/progress.json',
        'erosita_ls10_source_bytes':'erosita-ls10-source/receipt.json',
        'erosita_ls10_source_pin':'erosita-ls10-source/manifest.json',
        'erosita_ls10_decompressed':'erosita-ls10-evidence/decompressed.receipt.json',
        'erosita_ls10_fits_audit':'erosita-ls10-evidence/fits-audit.json',
        'erosita_ls10_owned_progress':'erosita-ls10-owned-evidence/progress.json',
        'erosita_ls10_owned_measurement':'erosita-ls10-owned-evidence/measurement.json',
        'erosita_ls10_exact_lookup':'erosita-ls10-owned-evidence/exact-lookup.json',
        'erosita_ls10_exact_lookup_progress':'erosita-ls10-owned-evidence/exact-lookup-progress.json',
        'simbad_basic_provider_count':'access-followup/simbad-basic-count-v2.json',
        'vsx_archived_versions_metadata':'access-followup/vsx-versions-receipt.json',
        'quaia_acquisition_retry':'access-followup/quaia-zenodo-api-receipt.json',
        'quaia_irsa_export_job':'quaia-irsa-source/job.json',
        'quaia_irsa_export_progress':'quaia-irsa-source/progress.json',
        'quaia_irsa_source_audit':'quaia-irsa-source/receipt.json',
        'quaia_owned_progress':'quaia-owned-evidence/progress.json',
        'quaia_owned_detail':'quaia-owned-evidence/detail.receipt.json',
        'quaia_owned_measurement':'quaia-owned-evidence/measurement.json',
        'nvss_full_field_audit':'nvss-owned-evidence/fields.receipt.json',
        'nvss_owned_progress':'nvss-owned-evidence/progress.json',
        'nvss_owned_detail':'nvss-owned-evidence/detail.receipt.json',
        'nvss_owned_measurement':'nvss-owned-evidence/measurement.json',
        'spiders_full_source_download':'acquisition/spiders-dr20-source-receipt.json',
        'spiders_full_source_audit':'acquisition/spiders-dr20-fits-audit.json',
        'spiders_owned_progress':'spiders-owned-evidence/progress.json',
        'spiders_owned_measurement':'spiders-owned-evidence/measurement.json',
        'spiders_exact_lookup':'spiders-owned-evidence/exact-lookup.json',
        'spiders_exact_lookup_progress':'spiders-owned-evidence/exact-lookup-progress.json',
        'virgo_full_source_measurement':'virgo-source/virgo-vcc--vcc.dat.json',
        'virgo_pinned_schema':'access-followup/virgo-readme-resolved-receipt.json',
        'snr_summary_source':'snr-source/supernova-remnants--snrs.dat.json',
        'snr_pinned_schema':'access-followup/snr-readme-receipt.json',
        'snr_summary_document':'snr-source/snr-catalogue2024-tables.pdf.receipt.json',
        'snr_detailed_document':'snr-source/snr-catalogue2024-table-V.pdf.receipt.json',
        'neargalcat_full_source':'neargalcat-source/full.tdat.gz.receipt.json',
        'neargalcat_owned_measurement':'neargalcat-measurement.json',
        'neargalcat_overlap':'neargalcat-source/local-volume-overlap.json',
        'neargalcat_documentation':'access-followup/neargalcat-doc-receipt.json',
        'cta_original_paper':'access-followup/cta-paper.pdf-receipt.json',
        'apm_original_discovery':'access-followup/apm-discovery-receipt.json',
        'apm_parent_catalog_documentation':'access-followup/apm-overview-receipt.json',
        'apm_access_documentation':'access-followup/apm-remote-notes-receipt.json',
        'apm_bulk_acquisition_gap':'apm-access/acquisition-gap.json',
        'existing_ephemeris_kernels':'existing-kernel-measurements.json',
        'exoplanet_download_progress':'exoplanets-source/retry-full/progress.json',
        'exoplanet_full_source':'exoplanets-source/retry-full/receipt.json',
        'atnf_owned_measurement':'atnf-owned-storage/measurement.json',
        'virgo_owned_measurement':'virgo-measurement.json',
        'snr_owned_measurement':'snr-measurement.json',
        'desi_source_progress':'desi-source/progress.json',
        'desi_source_feasibility':'desi-source/feasibility.json',
        'desi_source_manifest':'desi-source/manifest.json',
        'desi_complete_source_receipt':'desi-source/receipt.json',
        'desi_full_source_audit':'desi-source/full-audit.json',
        'desi_conversion_feasibility':'desi-conversion-feasibility.json',
        'desi_conversion_worker_progress':'desi-conversion-worker-progress.json',
        'desi_owned_partition_progress':'desi-owned-partitions/progress.json',
        'desi_owned_partition_measurement':'desi-owned-partitions/measurement.json',
        'desi_header_schema':'desi-source/header-schema.json',
        'desi_conversion_diagnostic_sample':'desi-conversion-probe/probe.json',
        'desi_lookup_diagnostic_sample':'desi-conversion-probe/lookup-probe.json',
        'legacy_sweep_manifest_inventory':'optical-access/legacy-sweep-inventory.json',
        'legacy_tractor_manifest_progress':'legacy-tractor-inventory/progress.json',
        'legacy_tractor_manifest_inventory':'legacy-tractor-inventory/inventory.json',
        'legacy_tractor_manifest_verification':'legacy-tractor-inventory/verification.json',
        'owned_worker_resource_adjustment':'owned-worker-resource-adjustment.json',
        'legacy_first_file_measurement':'legacy-tractor-first/measurement-scope.json',
        'legacy_first_file_semantics':'legacy-tractor-first/source-semantics.json',
        'legacy_known_issues':'optical-access/legacy-known-issues.receipt.json',
        'ps1_new_tap_access_gap':'optical-access/ps1-access-gap.json',
        'ps1_new_tap_table_list':'optical-access/ps1-table-list.receipt.json',
        'ps1_corrected_schema_inventory':'optical-access/ps1-schema-inventory.json',
        'sdss_acquisition_status':'sdss-access/acquisition-status.json',
        'sdss_run_listing_progress':'sdss-run-inventory/progress.json',
        'sdss_run_listing_inventory':'sdss-run-inventory/inventory.json',
        'sdss_run_listing_verification':'sdss-run-inventory/verification.json',
        'sdss_checksum_metadata_progress':'sdss-checksum-inventory/progress.json',
        'sdss_checksum_metadata_measurement':'sdss-checksum-inventory/measurement.json',
        'sdss_checksum_metadata_verification':'sdss-checksum-inventory/verification.json',
        'allwise_angular_feasibility':'allwise-angular-feasibility/feasibility.json',
        'allwise_angular_provider_documentation':'allwise-angular-feasibility/documentation-receipt.json',
        'sdss_first_file_measurement':'sdss-first-source/measurement-scope.json',
        'repository_compilations':'repository-compilation-measurements.json',
        'static_compilations':'static-compilation-measurements.json',
        'sb_sat_complete_measurement':'sb-sat-measurement.json',
        'spacecraft_inventory_measurement':'spacecraft-inventory-measurement.json',
        'spacecraft_target_metadata_progress':'spacecraft-source/target-metadata/progress.json',
        'spacecraft_target_metadata_measurement':'spacecraft-source/target-metadata/measurement.json',
        'spacecraft_target_metadata_verification':'spacecraft-source/target-metadata/verification-complete.json',
        'bzcat_candidate_measurement':'bzcat-measurement.json',
        'exoplanet_owned_progress':'exoplanets-owned-evidence/progress.json',
        'exoplanet_owned_measurement':'exoplanets-owned-evidence/measurement.json',
        'exoplanet_exact_lookup':'exoplanets-owned-evidence/exact-lookup.json',
        'exoplanet_exact_lookup_progress':'exoplanets-owned-evidence/exact-lookup-progress.json',
        'sbdb_provider_schema':'small-body-source/info-all.json',
        'sbdb_pilot_1000':'small-body-source/pilot-1000.receipt.json',
        'sbdb_pilot_10000':'small-body-source/pilot-10000.receipt.json',
        'sbdb_full_download_progress':'small-body-source/full/progress.json',
        'sbdb_full_source':'small-body-source/full/receipt.json',
        'vsx_provider_probe':'vsx-source/acquisition-probe.json',
        'vsx_full_source':'vsx-source/full/variables--vsx.dat.json',
        'psc_remote_index_trial':'psc-remote-trial.json',
        'sbdb_compression_probe':'small-body-source/compression-probe.json',
        'sbdb_remote_retry':'sbdb-remote-retry.json',
        'quaia_apps_server_probe':'access-followup/quaia-apps-head.json',
        'vsx_references_source':'vsx-source/references/variables--refs.dat.json',
        'psc_index_trial_measurement':'psc-remote-evidence/lookup.receipt.json',
        'psc_index_trial_queries':'psc-remote-evidence/query-benchmark.json',
        'sbdb_category_acquisition':'sbdb-categories-remote.json',
        'psc_full_index_remote':'psc-full-index-remote.json',
        'psc_remote_input_sync':'psc-full/remote-sync-progress.json',
        'vsx_post_acquisition_metadata':'vsx-source/post-acquisition-metadata.json',
        'sbdb_category_measurements':'sbdb-category-evidence/measurement.json',
        'sbdb_category_counts_before':'sbdb-category-evidence/before-provider-counts.json',
        'sbdb_category_counts_after':'sbdb-category-evidence/after-provider-counts.json',
        'sbdb_global_reconciliation':'sbdb-category-evidence/reconciliation.receipt.json',
        'sbdb_independent_census':'sbdb-category-evidence/independent-census.receipt.json',
        'sbdb_owned_storage_run':'sbdb-storage-remote.json',
        'vsx_remote_field_audit_transfer':'vsx-source/remote-transfer-worker.json',
        'allwise_full_run':'allwise-full-remote.json',
        'allwise_first_new_partition':'allwise-remote-evidence/first-partition.json',
        'allwise_measured_progress':'allwise-remote-evidence/summary.json',
        'allwise_lookup_trial':'allwise-remote-evidence/lookup-trial.receipt.json',
        'allwise_packed_id_trial':'allwise-remote-evidence/packed-trial.receipt.json',
        'allwise_packed_full_progress':'allwise-remote-evidence/packed-full-progress.json',
        'allwise_packed_full_workspace':'allwise-remote-evidence/packed-full-workspace.json',
        'allwise_packed_full_measurement':'allwise-remote-evidence/packed-full-measurement.json',
        'psc_global_index_progress':'psc-remote-evidence/full-build-progress.json',
        'psc_global_index_workspace':'psc-remote-evidence/full-build-workspace.json',
        'sbdb_owned_measurement':'sbdb-owned-evidence/measurement.json',
        'vsx_field_audit':'vsx-source/fields.receipt.json',
        'vsx_owned_storage_run':'vsx-storage-remote.json',
        'vsx_owned_measurement':'vsx-owned-evidence/measurement.json',
        'vsx_full_detail_measurement':'vsx-owned-evidence/detail.receipt.json',
        'openngc_owned_measurement':'openngc-owned-evidence/measurement.json',
        'openngc_evidence_index':'openngc-owned-evidence/evidence-index.json',
        'workspace_resumed_observed_peak':'workspace-observed-peak-resume-20260910.json',
    }.items():
        if (WORK/path).exists():ledger[key]=read(WORK/path)
    additional=[]
    for p in sorted((WORK/'additional-sources').glob('*.json')):
        if p.name in ('manifest.json','worker.json'):continue
        row=read(p)
        if 'status' in row:additional.append(row)
    ledger['additional_complete_source_file_receipts']=additional
    known_ids={entry['id'] for entry in ledger['catalogs']}
    groups={}
    for row in additional:
        if row['status']!='full_source_measured':continue
        key=row['id'].split('--')[0]
        if key not in known_ids:raise ValueError('source receipt absent from inventory: '+key)
        groups.setdefault(key,[]).append(row)
    ledger['additional_acquisition_followup']=read(WORK/'access-followup/receipts.json')
    ledger['additional_catalog_schema_receipts']=read(WORK/'extra-catalog-docs/receipts.json')
    ledger['radio_table_measurements']={}
    ledger['specialist_table_measurements']={}
    specialist_specs={'clusters':('clusters-owned-storage',['catalog']),
        'nebulae':('nebulae-owned-storage',['main.dat','diam.dat','dist.dat','dista.dat','hbeta.dat','intens.dat',
                    'iue.dat','iras.dat','nir.dat','radio.dat','vel.dat','cstar.dat','notes.dat','pospn.dat','notpn.dat','refs.dat'])}
    for family,(directory,tables) in specialist_specs.items():
        ledger['specialist_table_measurements'][family]={}
        for table in tables:
            root=WORK/directory/(family+'--'+table)
            if (root/'table/measurement.json').exists():
                r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
                if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
                if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
                ledger['specialist_table_measurements'][family][table]=r
    ledger['markarian_table_measurements']={}
    for table in ['table7.dat','notes.dat','table6.dat','table8.dat','table9.dat','table10.dat','refs.dat']:
        name='markarian--'+table;root=WORK/'markarian-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
            ledger['markarian_table_measurements'][name]=r
    ledger['twoqz_table_measurements']={}
    for table in ['2qz.dat','ngp_rep.dat','sgp_rep.dat','6qz_rep.dat']:
        name='2qz--'+table;root=WORK/'2qz-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
            ledger['twoqz_table_measurements'][name]=r
    ledger['twomrs_table_measurements']={}
    for table in [f'table{i}.dat' for i in [3,4,6,7,8,9,10,11,12,13]]:
        name='2mrs--'+table;root=WORK/'2mrs-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
            ledger['twomrs_table_measurements'][name]=r
    ledger['abell_table_measurements']={}
    for table in ['table3.dat','table4.dat','table5.dat','table6.dat','notes.dat']:
        name='abell--'+table;root=WORK/'abell-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
            ledger['abell_table_measurements'][name]=r
    ledger['fornax_table_measurements']={}
    for table in ['p2tbl2.dat','p2tbl3.dat','notes.dat']+[f'p3tbl{i}.dat' for i in range(2,7)]:
        name='fornax-cluster--'+table;root=WORK/'fornax-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            if (root/'expanded.receipt.json').exists():r['expanded']=read(root/'expanded.receipt.json')
            ledger['fornax_table_measurements'][name]=r
    ledger['local_volume_table_measurements']={}
    for table in ['table1.dat','table2.dat','table3.dat','table4.dat','table5.dat','table6.dat','refs.dat']:
        name='local-volume--'+table;root=WORK/'local-volume-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            ledger['local_volume_table_measurements'][name]=r
    ledger['bass_table_measurements']={}
    for name in ['bass-dr2--table8.dat','bass-dr2--table9.dat','bass-dr2--table11.dat']:
        root=WORK/'bass-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            ledger['bass_table_measurements'][name]=r
    ledger['sixdf_table_measurements']={}
    for table in ['6dfgs.dat','spectra.dat']:
        root=WORK/'6df-owned-evidence'/table
        ledger['sixdf_table_measurements'][table]={}
        for artifact in ['expanded.receipt.json','fields.receipt.json','table/progress.json','table/measurement.json','lookup/progress.json','lookup/measurement.json']:
            if (root/artifact).exists():ledger['sixdf_table_measurements'][table][artifact]=read(root/artifact)
    for name in ['3c--3c.dat','3c--3cr.dat','4c--radio4c.dat']:
        root=WORK/'radio-owned-storage'/name
        if (root/'table/measurement.json').exists():
            r={'audit':read(root/'fields.receipt.json'),'data':read(root/'table/measurement.json')}
            if (root/'lookup/measurement.json').exists():r['lookup']=read(root/'lookup/measurement.json')
            ledger['radio_table_measurements'][name]=r
    ledger['small_source_release_measurements']={
        'hipparcos':read(WORK/'small-releases/hipparcos-receipt.json'),
        'atnf_package':read(WORK/'small-releases/receipts.json'),
        'atnf_content':read(WORK/'small-releases/psrcat-content.json')}
    for entry in ledger['catalogs']:
        if entry['id']=='2mass-psc' and 'psc_completion_audit' in ledger:
            r=ledger['psc_completion_audit']
            if r['files']!=92 or r['rows']!=470992970 or not r['all_92_projection_sha256_and_parquet_counts_reverified']:
                raise ValueError('invalid full PSC completion audit')
            entry['status']='source_and_candidate_data_measured_serving_incomplete'
            entry['artifacts']['complete_source'].update(
                status='measured_all_92_source_files',logical_bytes=r['source_bytes'],
                evidence='psc-full/completion-audit.json')
            entry['artifacts']['full_schema_detail'].update(
                status='measured_all_60_fields_candidate_not_admitted_native_storage',
                logical_bytes=r['candidate_data_bytes'],
                allocated_bytes=r['candidate_data_allocated_bytes_sum'],
                evidence='psc-full/completion-audit.json')
        if entry['id'] in specialist_specs:
            components=ledger['specialist_table_measurements'][entry['id']]
            if len(components)==len(specialist_specs[entry['id']][1]):
                for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                    if all(artifact in c for c in components.values()):
                        entry['artifacts'][key].update(status='measured_all_pinned_specialist_structured_tables',
                            logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                            allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                            tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='markarian' and len(ledger['markarian_table_measurements'])==7:
            components=ledger['markarian_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_seven_structured_Markarian_tables_document_retained_separately',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='2qz' and len(ledger['twoqz_table_measurements'])==4:
            components=ledger['twoqz_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_complete_2QZ_6QZ_catalogue_and_repeat_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='2mrs' and len(ledger['twomrs_table_measurements'])==10:
            components=ledger['twomrs_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_all_ten_pinned_2MRS_science_quality_reference_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='abell' and len(ledger['abell_table_measurements'])==5:
            components=ledger['abell_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_all_five_pinned_Abell_structured_tables_document_retained_separately',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='fornax-cluster' and len(ledger['fornax_table_measurements'])==8:
            components=ledger['fornax_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_all_eight_pinned_Fornax_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='local-volume' and len(ledger['local_volume_table_measurements'])==7:
            components=ledger['local_volume_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_all_seven_pinned_science_and_reference_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='bass-dr2' and len(ledger['bass_table_measurements'])==3:
            components=ledger['bass_table_measurements']
            for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_all_three_pinned_BASS_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id']=='6df':
            components=ledger['sixdf_table_measurements']
            for artifact,key in [('table/measurement.json','full_schema_detail'),('lookup/measurement.json','id_routing')]:
                if all(artifact in c for c in components.values()):
                    entry['artifacts'][key].update(status='measured_complete_catalogue_and_spectrum_metadata_tables',
                        logical_bytes=sum(c[artifact]['bytes'] for c in components.values()),
                        allocated_bytes=sum(c[artifact]['allocated_bytes'] for c in components.values()),
                        tables={name:c[artifact] for name,c in components.items()})
        if entry['id'] in ['3c','4c']:
            names=['3c--3c.dat','3c--3cr.dat'] if entry['id']=='3c' else ['4c--radio4c.dat']
            if all(n in ledger['radio_table_measurements'] for n in names):
                components=[ledger['radio_table_measurements'][n] for n in names]
                entry['artifacts']['full_schema_detail'].update(status='measured_all_pinned_radio_table_fields',
                    logical_bytes=sum(c['data']['bytes'] for c in components),
                    allocated_bytes=sum(c['data']['allocated_bytes'] for c in components),
                    tables={n:ledger['radio_table_measurements'][n]['data'] for n in names})
                if all('lookup' in c for c in components):
                    entry['artifacts']['id_routing'].update(status='measured_exact_source_names_separate_releases',
                        logical_bytes=sum(c['lookup']['bytes'] for c in components),
                        allocated_bytes=sum(c['lookup']['allocated_bytes'] for c in components),
                        tables={n:ledger['radio_table_measurements'][n]['lookup'] for n in names})
        if entry['id']=='variables' and 'vsx_full_source' in ledger:
            r=ledger['vsx_full_source']
            entry['resolved_release']='CDS B/vsx main table 2026-08-23; full-file row accounting; field audit and reference table pending'
            entry['artifacts']['complete_source'].update(status='measured_full_main_table_field_audit_pending',
                logical_bytes=r['source_bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
            if 'vsx_field_audit' in ledger:
                entry['resolved_release']='CDS B/vsx main table 2026-08-23; all rows and 21 source fields audited; reference integration pending'
                entry['artifacts']['complete_source']['status']='measured_full_main_table_all_fields_audited'
            if 'vsx_full_detail_measurement' in ledger:
                stored=ledger['vsx_full_detail_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_full_main_table_detail',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],sha256=stored['sha256'])
            if 'vsx_owned_measurement' in ledger:
                stored=ledger['vsx_owned_measurement']
                entry['artifacts']['id_routing'].update(status='measured_ID_name_angular_component',
                    logical_bytes=stored['index_bytes'],allocated_bytes=stored['index_allocated_bytes'],
                    rows=stored['rows'],sha256=stored['index_sha256'])
        if entry['id']=='small-bodies' and 'sbdb_full_source' in ledger:
            r=ledger['sbdb_full_source']
            entry['resolved_release']='Full-precision unfiltered SBDB query snapshot; see receipt dates and signature'
            entry['artifacts']['complete_source'].update(status=r['status'],logical_bytes=r['source_bytes'],
                allocated_bytes=r['allocated_bytes'],rows=r['rows'],columns=r['columns'],sha256=r['sha256'])
        if entry['id']=='exoplanets' and 'exoplanet_full_source' in ledger:
            r=ledger['exoplanet_full_source']
            entry['resolved_release']='PSCompPars full-query snapshot; retrieval UNIX '+str(r['retrieval_started_unix'])
            entry['artifacts']['complete_source'].update(status=r['status'],logical_bytes=r['source_bytes'],
                allocated_bytes=r['allocated_bytes'],rows=r['rows'],columns=r['columns'],sha256=r['sha256'])
            if 'exoplanet_owned_measurement' in ledger:
                stored=ledger['exoplanet_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_all703_scalar_VOTable_fields',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],columns=stored['columns'],sha256=stored['sha256'])
            if 'exoplanet_exact_lookup' in ledger:
                stored=ledger['exoplanet_exact_lookup']
                entry['artifacts']['id_routing'].update(status='measured_exact_planet_host_catalogue_identifiers',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],entries=stored['entries'],fields=stored['fields'],sha256=stored['sha256'])
        if entry['id'] in {'solar-system-core','mars-satellites'} and 'existing_ephemeris_kernels' in ledger:
            filename='de440s.bsp' if entry['id']=='solar-system-core' else 'mar099s.bsp'
            r=next(r for r in ledger['existing_ephemeris_kernels'] if Path(r['file']).name==filename)
            entry['artifacts']['complete_source'].update(status='measured_complete_kernel_only_other_metadata_pending',
                logical_bytes=r['source_bytes'],allocated_bytes=r['allocated_bytes'],sha256=r['sha256'])
        if entry['id'] in {'solar-system-core','mars-satellites','giant-planet-satellites','nearby-stars-curated'} and 'static_compilations' in ledger:
            r=next(r for r in ledger['static_compilations'] if r['catalog']==entry['id'])
            entry['builtin_metadata_component']=r
            entry['artifacts']['full_schema_detail'].update(status='measured_builtin_metadata_JSON_only_ephemeris_or_upstream_data_separate',
                logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
            entry['acquisition_scope']='Complete current built-in metadata definitions only. Shared code files counted once; ephemeris/time coverage, upstream releases, runtime caches and serving artifacts remain separate.'
        if entry['id']=='spacecraft' and 'spacecraft_inventory_measurement' in ledger:
            r=ledger['spacecraft_inventory_measurement']
            entry['current_manifest_component']=r
            entry['artifacts']['full_schema_detail'].update(status='measured_current_application_metadata_manifest_only_trajectories_separate',
                logical_bytes=r['manifest_bytes'],allocated_bytes=r['manifest_allocated_bytes'],sha256=r['manifest_sha256'])
            entry['acquisition_scope']=r['scope']
        if entry['id']=='blazars' and 'bzcat_candidate_measurement' in ledger:
            entry['candidate_release_measurement']=ledger['bzcat_candidate_measurement']
            entry['acquisition_scope']=ledger['bzcat_candidate_measurement']['scope']
        if entry['id']=='apm' and 'apm_bulk_acquisition_gap' in ledger:
            entry['acquisition_gap']=ledger['apm_bulk_acquisition_gap']
        if entry['id']=='small-body-satellites' and 'sb_sat_complete_measurement' in ledger:
            r=ledger['sb_sat_complete_measurement']
            entry['resolved_release']='SB-SAT API 1.0 unfiltered snapshot; source SHA-256 '+r['source_sha256']
            entry['status']='full_api_snapshot_and_lookup_measured_native_ephemeris_pending'
            entry['artifacts']['complete_source'].update(status='measured_complete_requested_API_snapshot',
                logical_bytes=r['source_bytes'],sha256=r['source_sha256'],rows=r['rows'])
            entry['artifacts']['full_schema_detail'].update(status='measured_lossless_nested_JSONL_and_response_metadata',
                logical_bytes=r['data_bytes']+r['metadata_bytes'],
                allocated_bytes=r['data_allocated_bytes']+r['metadata_allocated_bytes'])
            entry['artifacts']['id_routing'].update(status='measured_exact_parent_and_available_satellite_names_not_identity_merging',
                logical_bytes=r['index_bytes'],allocated_bytes=r['index_allocated_bytes'],sha256=r['index_sha256'])
            entry['documentation_component']={k:r[k] for k in ('documentation_bytes','documentation_allocated_bytes','documentation_sha256')}
            entry['acquisition_scope']=r['scope']
        if entry['id']=='desi-dr1' and 'desi_source_progress' in ledger:
            entry['resolved_release']='DESI DR1 iron zcatalog v1 zall-pix-iron.fits; HTTP validators pinned'
            entry['source_acquisition_progress']=ledger['desi_source_progress']
            entry['acquisition_scope']='Full redshift summary file; other DESI source products and all serving artifacts remain unmeasured. Downloaded ranges are not validated catalog rows.'
        if entry['id']=='legacy-surveys' and 'legacy_sweep_manifest_inventory' in ledger:
            entry['resolved_release']='DR10 south Tractor; DR10.1 corrected standard/extra/light-curve/photo-z sweeps; checksums being pinned'
            entry['acquisition_scope']='Sweep families share records, not independent populations. Standard sweep omits columns and selects BRICK_PRIMARY; retain extra/light-curve fields and inventory all Tractor rows separately. Source bytes and row alignment remain unmeasured.'
            entry['provider_sweep_files']=ledger['legacy_sweep_manifest_inventory']['provider_file_count']
            if 'legacy_tractor_manifest_inventory' in ledger:
                entry['provider_tractor_files']=ledger['legacy_tractor_manifest_inventory']['provider_file_count']
                entry['provider_tractor_inventory_status']=ledger['legacy_tractor_manifest_inventory']['status']
        if entry['id']=='panstarrs' and 'ps1_new_tap_access_gap' in ledger:
            entry['acquisition_gap']='New official PS1 DR2 TAP advertises hard 100000-row output cap; full bulk acquisition remains unresolved. CasJobs alternative remains to be investigated; no full bytes inferred from provider database-size metadata.'
        if entry['id'] in {'messier','curated-landmarks'} and 'repository_compilations' in ledger:
            r=next(r for r in ledger['repository_compilations'] if r['catalog']==entry['id'])
            entry['resolved_release']='Owned compilation at git '+r['revision']
            for key in ['complete_source','full_schema_detail']:
                entry['artifacts'][key].update(status='measured_owned_compilation_same_JSON_artifact_count_once',
                    logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],
                    sha256=r['sha256'],artifact_id=r['artifact_id'])
            entry['acquisition_scope']='Complete checked-in compilation only, not complete coverage of referenced upstream catalogs. Source and stored JSON are the same artifact; count once.'
        if entry['id']=='cta' and 'cta_original_paper' in ledger:
            r=ledger['cta_original_paper']
            entry['resolved_release']=r['release']
            entry['artifacts']['complete_source'].update(status='measured_full_paper_table_transcription_pending',
                logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],sha256=r['sha256'],rows=None,
                provider_reported_rows=r['provider_reported_source_rows'])
        if entry['id']=='apm':
            entry['acquisition_scope']='POSS-I and UKST parent plate catalogs; source landmark found during halo carbon-star survey. Do not substitute Bright Galaxy or quasar subsets.'
            entry['acquisition_gap']='Official field-query documentation found; exact full releases and supported bulk archive remain unresolved.'
        if entry['id']=='heasarc-neargalcat' and 'neargalcat_full_source' in ledger:
            r=ledger['neargalcat_full_source']
            entry['resolved_release']=r['release_header']
            entry['artifacts']['complete_source'].update(status='measured_full_TDAT_table',logical_bytes=r['bytes'],
                allocated_bytes=r['allocated_bytes'],rows=r['rows'],columns=r['columns'],sha256=r['sha256'],
                uncompressed_bytes=r['uncompressed_bytes'])
            entry['overlap_evidence']='Same 869 exact names as Local Volume J/AJ/145/101 table1; RA/Dec within 5e-9 degrees and all distances equal; other field translations pending'
            if 'neargalcat_owned_measurement' in ledger:
                stored=ledger['neargalcat_owned_measurement']
                for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                    r=stored[artifact]
                    entry['artifacts'][key].update(status='measured_complete_NEARGALCAT_field_text_and_lookup_component',
                        logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
        if entry['id']=='supernova-remnants' and 'snr_summary_source' in ledger:
            r=ledger['snr_summary_source']
            entry['resolved_release']='Green 2024 October; CDS VII/297; 2025 publication'
            entry['artifacts']['complete_source'].update(status='measured_full_summary_table',logical_bytes=r['source_bytes'],
                allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
            entry['additional_source_scope']='Publisher full notes, references and possible/probable remnants in separately acquired PDFs; normalization pending'
            if 'snr_owned_measurement' in ledger:
                stored=ledger['snr_owned_measurement']
                for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                    r=stored[artifact]
                    entry['artifacts'][key].update(status='measured_full_summary_component_detailed_notes_pending',
                        logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
        if entry['id'] in groups:
            rows=groups[entry['id']]
            entry['acquired_file_set']={'status':'complete_named_files_measured_release_equivalence_pending',
                'files':len(rows),'source_bytes':sum(r['source_bytes'] for r in rows),
                'allocated_bytes':sum(r['allocated_bytes'] for r in rows),
                'uncompressed_bytes':sum(r['uncompressed_bytes'] for r in rows),
                'file_ids':[r['id'] for r in rows], 'provider_catalogs':sorted({r['catalog'] for r in rows})}
        if entry['id']=='openngc':
            r=next(r for r in read(WORK/'openngc/receipt.json') if r['file']=='database_files/NGC.csv')
            entry['artifacts']['complete_source'].update(status='measured_full_NGC_table',logical_bytes=r['bytes'],
                allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
            stored=ledger.get('openngc_owned_measurement')
            if stored:
                for artifact,name in [('full_schema_detail','detail.parquet'),('id_routing','lookup.sqlite')]:
                    component=stored['files'][name]
                    entry['artifacts'][artifact].update(status='measured_full_records_component',
                        logical_bytes=component['bytes'],allocated_bytes=component['allocated_bytes'],
                        sha256=component['sha256'],rows=stored['rows'])
                entry['remaining_serving_components']=stored['remaining']
            if 'openngc_evidence_index' in ledger:
                indexed=ledger['openngc_evidence_index']
                entry['artifacts']['published_evidence_and_angular']={
                    'status':'measured_combined_component_not_full_native_serving',
                    'logical_bytes':indexed['bytes'],'allocated_bytes':indexed['allocated_bytes'],
                    'sha256':indexed['sha256'],'rows':indexed['rows']}
                for key in ['aliases_text_search','angular_index']:
                    entry['artifacts'][key].update(status='component_measured_in_shared_artifact_native_integration_pending',
                        shared_artifact='published_evidence_and_angular',logical_bytes=None,allocated_bytes=None)
                entry['remaining_serving_components']=indexed['remaining']
        if entry['id']=='virgo-cluster' and 'virgo_full_source_measurement' in ledger:
            r=ledger['virgo_full_source_measurement']
            entry['resolved_release']='J/AJ/90/1681; Binggeli+ 1985; CDS ReadMe 2002-06-20; full vcc.dat'
            entry['artifacts']['complete_source'].update(
                status='measured_full_source',logical_bytes=r['source_bytes'],
                allocated_bytes=r['allocated_bytes'],uncompressed_bytes=r['uncompressed_bytes'],
                rows=r['rows'],sha256=r['sha256'])
            if 'virgo_owned_measurement' in ledger:
                stored=ledger['virgo_owned_measurement']
                for artifact,key in [('data','full_schema_detail'),('lookup','id_routing')]:
                    r=stored[artifact]
                    entry['artifacts'][key].update(status='measured_full_VCC_component_membership_flags_retained',
                        logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
        if entry['id']=='spiders-dr20' and 'spiders_full_source_audit' in ledger:
            r=ledger['spiders_full_source_audit']
            tables=[h for h in r['hdus'] if 'rows_read' in h]
            entry['artifacts']['complete_source'].update(
                status='measured_full_source_all_fields_read',
                logical_bytes=r['source_bytes'], allocated_bytes=r['allocated_bytes'],
                rows=sum(h['rows_read'] for h in tables), sha256=r['source_sha256'])
            if 'spiders_owned_measurement' in ledger:
                stored=ledger['spiders_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_all_FITS_table_fields_and_arrays',
                    logical_bytes=stored['detail_bytes'],allocated_bytes=stored['detail_allocated_bytes'],
                    tables=stored['tables'])
            if 'spiders_exact_lookup' in ledger:
                stored=ledger['spiders_exact_lookup']
                entry['artifacts']['id_routing'].update(status='measured_field_scoped_exact_lookup_all_locators_verified',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],entries=stored['entries'],fields=stored['fields'],sha256=stored['sha256'])
        if entry['id']=='quaia' and 'quaia_irsa_source_audit' in ledger:
            r=ledger['quaia_irsa_source_audit']
            entry['artifacts']['complete_source'].update(
                status='measured_full_IRSA_table_export_original_distribution_equivalence_pending',
                logical_bytes=r['source_bytes'],allocated_bytes=r['allocated_bytes'],
                rows=r['rows'],sha256=r['sha256'])
            entry['source_export_scope']=r['coverage_note']
            if 'quaia_owned_detail' in ledger:
                component=ledger['quaia_owned_detail']
                entry['artifacts']['full_schema_detail'].update(status='measured_all_archived_fields',
                    logical_bytes=component['bytes'],allocated_bytes=component['allocated_bytes'],
                    sha256=component['sha256'],rows=component['rows'])
            if 'quaia_owned_measurement' in ledger:
                component=ledger['quaia_owned_measurement']
                entry['artifacts']['id_routing'].update(status='measured_ID_counterpart_angular_component',
                    logical_bytes=component['index_bytes'],allocated_bytes=component['index_allocated_bytes'],
                    sha256=component['index_sha256'],rows=component['rows'])
        if entry['id']=='erosita-dr2' and 'erosita_main_source_bytes' in ledger:
            r=ledger['erosita_main_source_bytes']
            entry['artifacts']['complete_source'].update(
                status='full_file_bytes_measured_FITS_row_audit_pending',logical_bytes=r['bytes'],
                allocated_bytes=r['allocated_bytes'],rows=None,sha256=r['sha256'])
            if 'erosita_main_source_audit' in ledger:
                audited=ledger['erosita_main_source_audit']
                entry['artifacts']['complete_source'].update(
                    status='full_file_all_FITS_table_fields_audited',
                    rows=sum(h['rows_read'] for h in audited['hdus'] if 'rows_read' in h))
            if 'erosita_main_owned_measurement' in ledger:
                stored=ledger['erosita_main_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_all_FITS_table_fields',
                    logical_bytes=stored['detail_bytes'],allocated_bytes=stored['detail_allocated_bytes'],
                    tables=stored['tables'])
            if 'erosita_main_exact_lookup' in ledger:
                stored=ledger['erosita_main_exact_lookup']
                entry['artifacts']['id_routing'].update(status='measured_field_scoped_exact_lookup_all_locators_verified',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],entries=stored['entries'],fields=stored['fields'],sha256=stored['sha256'])
        if entry['id']=='erosita-ls10' and 'erosita_ls10_source_bytes' in ledger:
            r=ledger['erosita_ls10_source_bytes']
            entry['artifacts']['complete_source'].update(status='compressed_file_bytes_measured_gzip_FITS_audit_pending',
                logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=None,sha256=r['sha256'])
            if 'erosita_ls10_fits_audit' in ledger:
                audited=ledger['erosita_ls10_fits_audit']
                entry['artifacts']['complete_source'].update(status='full_crossmatch_source_all_FITS_fields_audited',
                    uncompressed_bytes=audited['source_bytes'],
                    rows=sum(h['rows_read'] for h in audited['hdus'] if 'rows_read' in h))
            if 'erosita_ls10_owned_measurement' in ledger:
                stored=ledger['erosita_ls10_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_all_FITS_crossmatch_table_fields',
                    logical_bytes=stored['detail_bytes'],allocated_bytes=stored['detail_allocated_bytes'],
                    tables=stored['tables'])
            if 'erosita_ls10_exact_lookup' in ledger:
                stored=ledger['erosita_ls10_exact_lookup']
                entry['artifacts']['id_routing'].update(status='measured_field_scoped_exact_lookup_all_locators_verified',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],entries=stored['entries'],fields=stored['fields'],sha256=stored['sha256'])
        if entry['id']=='hipparcos':
            r=ledger['small_source_release_measurements']['hipparcos']
            entry['artifacts']['complete_source'].update(status='measured_full_main_table',logical_bytes=r['bytes'],allocated_bytes=r['allocated_bytes'],rows=r['rows'],sha256=r['sha256'])
            if 'hipparcos_full_field_audit' in ledger:
                audited=ledger['hipparcos_full_field_audit']
                if audited['status']=='SOURCE_FIELDS_AUDITED':
                    entry['artifacts']['complete_source'].update(status='measured_full_main_table_all_fields_audited',
                        columns=audited['columns'],schema_sha256=audited['readme_sha256'])
            if 'hipparcos_owned_measurement' in ledger:
                stored=ledger['hipparcos_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_all78_source_fields',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],columns=stored['columns'],sha256=stored['sha256'])
            if 'hipparcos_exact_lookup' in ledger:
                stored=ledger['hipparcos_exact_lookup']
                entry['artifacts']['id_routing'].update(status='measured_field_scoped_exact_lookup_all_locators_verified',
                    logical_bytes=stored['bytes'],allocated_bytes=stored['allocated_bytes'],
                    rows=stored['rows'],entries=stored['entries'],fields=stored['fields'],sha256=stored['sha256'])
        if entry['id']=='nvss' and 'nvss_full_field_audit' in ledger:
            audited=ledger['nvss_full_field_audit']
            if audited['status']=='SOURCE_FIELDS_AUDITED':
                entry['artifacts']['complete_source'].update(status='measured_full_source_all29_fields_audited',
                    logical_bytes=audited['source_bytes'],uncompressed_bytes=audited['uncompressed_bytes'],
                    rows=audited['rows'],columns=audited['columns'],sha256=audited['source_sha256'])
            if 'nvss_owned_detail' in ledger:
                component=ledger['nvss_owned_detail']
                entry['artifacts']['full_schema_detail'].update(status='measured_all29_source_fields',
                    logical_bytes=component['bytes'],allocated_bytes=component['allocated_bytes'],
                    rows=component['rows'],sha256=component['sha256'])
            if 'nvss_owned_measurement' in ledger:
                component=ledger['nvss_owned_measurement']
                entry['artifacts']['id_routing'].update(status='measured_record_name_angular_component',
                    logical_bytes=component['index_bytes'],allocated_bytes=component['index_allocated_bytes'],
                    rows=component['rows'],sha256=component['index_sha256'])
        if entry['id']=='pulsars':
            entry['resolved_release']='2.8.1; full source package and 4393 database records acquired; serving artifacts pending'
            r=next(r for r in ledger['small_source_release_measurements']['atnf_package'] if r['file']=='psrcat_pkg.v2.8.1.tar.gz')
            entry['artifacts']['complete_source'].update(status='measured_full_distribution_package',logical_bytes=r['bytes'],
                allocated_bytes=r['allocated_bytes'],rows=4393,sha256=r['sha256'])
            if 'atnf_owned_measurement' in ledger:
                stored=ledger['atnf_owned_measurement']
                entry['artifacts']['full_schema_detail'].update(status='measured_lossless_source_record_blocks_typed_hydration_pending',
                    logical_bytes=stored['detail_bytes'],allocated_bytes=stored['detail_allocated_bytes'],
                    rows=stored['rows'],sha256=stored['detail_sha256'],
                    source_field_occurrences=stored['source_field_occurrences'])
                entry['artifacts']['id_routing'].update(status='measured_PSRJ_PSRB_exact_lookup',
                    logical_bytes=stored['index_bytes'],allocated_bytes=stored['index_allocated_bytes'],
                    rows=stored['rows'],sha256=stored['index_sha256'])
    ledger['status']='INCOMPLETE'
    ledger['full_source_bytes']=None;ledger['full_serving_bytes']=None
    temporary=LEDGER.with_suffix('.json.tmp')
    with temporary.open('w') as f:json.dump(ledger,f,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
    temporary.replace(LEDGER)
    table=ROOT/'docs/catalog-storage-measured-progress.md'
    temporary=table.with_suffix('.md.tmp');temporary.write_text(progress_table(ledger));temporary.replace(table)
    print(json.dumps({'gaia':measured,'additional_verified_source_files':sum(r['status']=='full_source_measured' for r in additional),'additional_failed_source_files':sum(r['status']!='full_source_measured' for r in additional)}))

if __name__=='__main__':main()
