/** Curated object summaries, German. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Die Sonne ist der Ankerpunkt aller Umlaufbahnen des Sonnensystems im Atlas und liefert den Referenzmaßstab für Masse, Radius und Leuchtkraft von Sternen.",
  mercury: "Merkur ist der innerste Planet und zeigt, wie die Aufheizung durch die Sonne und die Gezeitengeschichte kleine Gesteinswelten prägen.",
  venus: "Venus ist in der Größe beinahe ein Zwilling der Erde, aber ein klimatisches Extrem, was sie zu einem wichtigen Vergleichspunkt für die Entwicklung terrestrischer Planeten macht.",
  earth: "Die Erde ist die Beobachtungsbasis des Atlas und die einzige bekannte bewohnte Welt und verknüpft die Position am Himmel mit lokaler Entfernung und lokalem Maßstab.",
  moon: "Der Mond bewahrt die Geschichte von Einschlägen und Vulkanismus und ist nah genug, um Details im Teleskop mit der Geologie des Raumfahrtzeitalters zu verbinden.",
  mars: "Mars ist abgesehen von der Erde der am besten erforschte nahe Gesteinsplanet und eine Referenz für Klimaverlust, Vulkanismus und die Erkundung der Oberfläche.",
  jupiter: "Jupiter beherrscht die Dynamik des Sonnensystems, und seine großen Monde bilden eine kompakte Vergleichsgruppe geologisch vielfältiger Welten.",
  saturn: "Saturn verbindet den Aufbau von Riesenplaneten, Ringe und Mondsysteme in einem der klarsten natürlichen Labore des Sonnensystems.",
  uranus: "Uranus ist ein Eisriese mit extremer Achsneigung, nützlich für den Vergleich des Inneren der äußeren Planeten und der jahreszeitlichen Geometrie.",
  neptune: "Neptun ist der Ankerpunkt der äußeren klassischen Planeten und zeigt, wie eine schnelle atmosphärische Dynamik weit entfernt von der Sonne bestehen bleibt.",
  pluto: "Pluto verbindet Zwergplaneten, die Geschichte des Kuipergürtels und die Geologie flüchtiger Stoffe am Rand des Planetensystems.",
  io: "Io ist der vulkanisch aktivste Mond des Sonnensystems, angetrieben durch Gezeitenheizung im Mondsystem des Jupiter.",
  europa: "Europa ist ein besonders wertvolles Ziel unter den Ozeanwelten, weil die eisige Oberfläche wahrscheinlich über einem globalen salzigen Ozean liegt.",
  ganymede: "Ganymed ist der größte Mond des Sonnensystems und der einzige Mond, von dem bekannt ist, dass er ein eigenes Magnetfeld erzeugt.",
  callisto: "Kallisto dokumentiert uralte Einschläge im äußeren Sonnensystem und steht in starkem Kontrast zu den aktiveren inneren Galileischen Monden.",
  titan: "Titan ist der einzige Mond mit dichter Atmosphäre und stabilen Flüssigkeiten an der Oberfläche und damit zentral für die vergleichende Planetenchemie.",
  enceladus: "Enceladus stößt Material aus einem Ozean unter der Oberfläche ins All aus und ist damit eines der direktesten Ziele für die Beprobung einer Ozeanwelt.",
  m13: "M13 ist ein Referenz-Kugelsternhaufen des Nordhimmels und zeigt eine dichte, alte Sternpopulation im Halo der Milchstraße.",
  m31: "Die Andromedagalaxie ist die nächstgelegene große Spiralgalaxie und stellt die Milchstraße in den direkten Zusammenhang der Lokalen Gruppe.",
  m42: "Der Orionnebel ist ein nahes Entstehungsgebiet massereicher Sterne, in dem junge Sterne das Gas und den Staub beleuchten, aus denen sie entstanden sind.",
  m45: "Die Plejaden sind ein naher, junger offener Sternhaufen, nützlich zum Ablesen von Sternfarbe, Alter und Reflexionsnebeln.",
  m57: "Der Ringnebel zeigt eine späte Entwicklungsphase sonnenähnlicher Sterne, in der ausgestoßenes Gas einen heißen zentralen Überrest umgibt.",
};

/** Title and alternative text of each curated image. English is in ../../objectMedia.ts. */
export const CURATED_MEDIA_TEXT: Record<string, { title: string; alt: string }> = {
  sun: { title: "Ansicht der gesamten Sonnenscheibe", alt: "Ansicht der gesamten Sonnenscheibe, aufgenommen vom Solar Dynamics Observatory." },
  mercury: { title: "Die Geheimnisse des Merkur enthüllen", alt: "MESSENGER-Ansicht des Merkur in verstärkten Farben." },
  venus: { title: "Venus – Globalansicht, zentriert auf 90 Grad östlicher Länge", alt: "Computersimulierte globale Radaransicht der Venus." },
  earth: { title: "Blaue Murmel 2012", alt: "Ansicht der gesamten Erdscheibe aus dem Weltraum mit blauen Ozeanen, weißen Wolken und sichtbaren Kontinenten." },
  moon: { title: "Die Vorderseite des Erdmonds, aufgenommen von Clementine", alt: "Globales Mosaik der Vorderseite des Erdmonds." },
  phobos: { title: "Phobos aus 6800 Kilometern Entfernung", alt: "Farbansicht des Marsmonds Phobos, aufgenommen vom Mars Reconnaissance Orbiter." },
  deimos: { title: "Die Monde des Mars", alt: "NASA-Bild der Marsmonde Phobos und Deimos." },
  mars: { title: "Tharsis-Vulkane und Valles Marineris", alt: "Globale Ansicht des Mars mit der Vulkanregion Tharsis und dem langen Canyonsystem Valles Marineris." },
  jupiter: { title: "Hochaufgelöster Globus des Jupiter", alt: "Farbiger Globus des Jupiter mit Wolkenbändern und dem Großen Roten Fleck." },
  io: { title: "Aktive Lavaströme am Vulkan Prometheus auf Io", alt: "Galileo-Ansicht vulkanischer Aktivität auf Io im nahen Infrarot." },
  europa: { title: "Spuren von Tonmineralen auf Europa", alt: "NASA-Bild des zerklüfteten Eisgeländes von Europa." },
  ganymede: { title: "Stereoansicht der Galileo-Region auf Ganymed", alt: "Gefurchtes Gelände auf Ganymed, aufgenommen von der Raumsonde Galileo." },
  callisto: { title: "Globale Farbansicht von Kallisto", alt: "Globales Farbbild des Jupitermonds Kallisto." },
  saturn: { title: "Über prachtvolle Ringe hinweg", alt: "Cassini-Ansicht des Saturn und seiner Ringebene." },
  enceladus: { title: "Enceladus, der Geysirmond des Saturn", alt: "Cassini-Ansicht von Enceladus mit hellem, eisigem Gelände." },
  titan: { title: "Leuchtender Titan", alt: "Cassini-Bild von Titan mit atmosphärischem Dunst." },
  uranus: { title: "Uranus, gesehen von Voyager 2", alt: "Aufnahme von Voyager 2: Uranus als blaugrüne Scheibe." },
  neptune: { title: "Neptun, aufgenommen von Voyager 2", alt: "Aufnahme von Voyager 2: Neptun mit blauen atmosphärischen Strukturen." },
  pluto: { title: "Globale Mosaike von Pluto und Charon", alt: "Globale Mosaike von Pluto und Charon, aufgenommen von New Horizons." },
  m31: { title: "Hubbles hochaufgelöster Panoramablick auf die Andromedagalaxie", alt: "Breites Hubble-Mosaik der Andromedagalaxie mit dichten Sternfeldern und Staubbändern." },
  m5: { title: "Messier 5", alt: "Hubble-Bild des Kugelsternhaufens Messier 5." },
  m11: { title: "M11 – Wildentenhaufen", alt: "Hubble-Bild des Wildentenhaufens, eines offenen Sternhaufens." },
  m13: { title: "M13 – Kugelsternhaufen", alt: "Hubble-Bild des dichten Kugelsternhaufens Messier 13." },
  m42: { title: "Orionnebel und Bugstoßwelle", alt: "Hubble-Ansicht von leuchtendem Gas und Staub im Orionnebel." },
  m45: { title: "Die Sieben Schwestern", alt: "Infrarotansicht des Sternhaufens Plejaden und des Staubs in seiner Umgebung." },
  m44: { title: "Messier 44 – ACS-Aufnahme", alt: "Hubble-Blick durch die Außenbereiche des Sternhaufens Praesepe (Krippe)." },
  m57: { title: "Blick durch eine Gasröhre auf einen todgeweihten Stern", alt: "Hubble-Bild des Ringnebels mit leuchtendem Gas um einen Zentralstern." },
};
