/** Curated object summaries, German. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Die Sonne ist der Ankerpunkt aller Umlaufbahnen des Sonnensystems im Atlas und liefert den Referenzmaßstab für Masse, Radius und Leuchtkraft von Sternen.",
  mercury: "Merkur ist der innerste Planet und zeigt, wie die Aufheizung durch die Sonne und die Gezeitengeschichte kleine Gesteinswelten prägen.",
  venus: "Venus ist in der Größe beinahe ein Zwilling der Erde, aber ein klimatisches Extrem, was sie zu einem wichtigen Vergleichspunkt für die Entwicklung terrestrischer Planeten macht.",
  earth: "Die Erde ist die Beobachtungsbasis des Atlas und die einzige bekannte bewohnte Welt und verknüpft die Position am Himmel mit lokaler Entfernung und lokalem Maßstab.",
  moon: "Der Mond bewahrt die Geschichte von Einschlägen und Vulkanismus und ist nah genug, um Details im Teleskop mit der Geologie des Raumfahrtzeitalters zu verbinden.",
  mars: "Mars ist abgesehen von der Erde der am besten erforschte nahe Gesteinsplanet und eine Referenz für Klimaverlust, Vulkanismus und die Erkundung der Oberfläche.",
  jupiter: "Jupiter beherrscht die Dynamik des Sonnensystems, und seine großen Monde bilden eine kompakte Vergleichsgruppe geologisch vielfältiger Welten.",
  saturn: "Saturn verbindet den Aufbau von Riesenplaneten, Ringe und Mondsysteme in einem der klarsten natürlichen Labore des Sonnensystems.",
  uranus: "Uranus ist ein Eisriese mit extremer Achsneigung, nützlich für den Vergleich des Inneren der äußeren Planeten und der jahreszeitlichen Geometrie.",
  neptune: "Neptun ist der Ankerpunkt der äußeren klassischen Planeten und zeigt, wie eine schnelle atmosphärische Dynamik weit entfernt von der Sonne bestehen bleibt.",
  pluto: "Pluto verbindet Zwergplaneten, die Geschichte des Kuipergürtels und die Geologie flüchtiger Stoffe am Rand des Planetensystems.",
  io: "Io ist der vulkanisch aktivste Mond des Sonnensystems, angetrieben durch Gezeitenheizung im Mondsystem des Jupiter.",
  europa: "Europa ist ein besonders wertvolles Ziel unter den Ozeanwelten, weil die eisige Oberfläche wahrscheinlich über einem globalen salzigen Ozean liegt.",
  ganymede: "Ganymed ist der größte Mond des Sonnensystems und der einzige Mond, von dem bekannt ist, dass er ein eigenes Magnetfeld erzeugt.",
  callisto: "Kallisto dokumentiert uralte Einschläge im äußeren Sonnensystem und steht in starkem Kontrast zu den aktiveren inneren Galileischen Monden.",
  titan: "Titan ist der einzige Mond mit dichter Atmosphäre und stabilen Flüssigkeiten an der Oberfläche und damit zentral für die vergleichende Planetenchemie.",
  enceladus: "Enceladus stößt Material aus einem Ozean unter der Oberfläche ins All aus und ist damit eines der direktesten Ziele für die Beprobung einer Ozeanwelt.",
  m13: "M13 ist ein Referenz-Kugelsternhaufen des Nordhimmels und zeigt eine dichte, alte Sternpopulation im Halo der Milchstraße.",
  m31: "Die Andromedagalaxie ist die nächstgelegene große Spiralgalaxie und stellt die Milchstraße in den direkten Zusammenhang der Lokalen Gruppe.",
  m42: "Der Orionnebel ist ein nahes Entstehungsgebiet massereicher Sterne, in dem junge Sterne das Gas und den Staub beleuchten, aus denen sie entstanden sind.",
  m45: "Die Plejaden sind ein naher, junger offener Sternhaufen, nützlich zum Ablesen von Sternfarbe, Alter und Reflexionsnebeln.",
  m57: "Der Ringnebel zeigt eine späte Entwicklungsphase sonnenähnlicher Sterne, in der ausgestoßenes Gas einen heißen zentralen Überrest umgibt.",
};
