/** Curated object summaries, Spanish. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "El Sol es el ancla de todas las órbitas del Sistema Solar en el atlas y proporciona la escala de referencia para la masa, el radio y la luminosidad de las estrellas.",
  mercury: "Mercurio es el planeta más interior y muestra cómo el calentamiento solar y la historia de las mareas dan forma a los mundos rocosos pequeños.",
  venus: "Venus es casi un gemelo de la Tierra en tamaño, pero un extremo climático, lo que lo convierte en un punto de comparación clave para la evolución de los planetas terrestres.",
  earth: "La Tierra es la referencia de observación del atlas y el único mundo habitado conocido, y vincula la posición en el cielo con la distancia y la escala locales.",
  moon: "La Luna conserva una historia de impactos y volcanismo, y está lo bastante cerca como para conectar el detalle telescópico con la geología de la era de las naves espaciales.",
  mars: "Marte es el planeta rocoso cercano mejor estudiado aparte de la Tierra y una referencia para la pérdida del clima, el volcanismo y la exploración de la superficie.",
  jupiter: "Júpiter domina la dinámica del Sistema Solar, y sus lunas principales forman un conjunto compacto de comparación de mundos geológicamente diversos.",
  saturn: "Saturno reúne la estructura de los planetas gigantes, los anillos y los sistemas de lunas en uno de los laboratorios naturales más claros del Sistema Solar.",
  uranus: "Urano es un gigante de hielo con una inclinación axial extrema, útil para comparar los interiores de los planetas exteriores y la geometría estacional.",
  neptune: "Neptuno es el ancla de los planetas clásicos exteriores y muestra cómo una dinámica atmosférica rápida persiste lejos del Sol.",
  pluto: "Plutón conecta los planetas enanos, la historia del cinturón de Kuiper y la geología de volátiles en el borde del sistema planetario.",
  io: "Ío es la luna con más actividad volcánica del Sistema Solar, impulsada por el calentamiento de marea dentro del sistema de lunas de Júpiter.",
  europa: "Europa es un objetivo de gran valor entre los mundos oceánicos, porque su superficie helada probablemente cubre un océano global salado.",
  ganymede: "Ganimedes es la luna más grande del Sistema Solar y la única luna de la que se sabe que genera su propio campo magnético.",
  callisto: "Calisto registra impactos antiguos del Sistema Solar exterior y contrasta fuertemente con las lunas galileanas interiores, más activas.",
  titan: "Titán es la única luna con una atmósfera densa y líquidos estables en la superficie, lo que la hace central para la química planetaria comparada.",
  enceladus: "Encélado expulsa al espacio material de un océano subsuperficial, lo que lo convierte en uno de los objetivos más directos para tomar muestras de un mundo oceánico.",
  m13: "M13 es un cúmulo globular de referencia del cielo boreal y muestra una población estelar densa y antigua en el halo de la Vía Láctea.",
  m31: "Andrómeda es la galaxia espiral grande más cercana y sitúa la Vía Láctea en el contexto directo del Grupo Local.",
  m42: "La Nebulosa de Orión es una región cercana de formación de estrellas masivas, donde las estrellas jóvenes iluminan el gas y el polvo en los que nacieron.",
  m45: "Las Pléyades son un cúmulo abierto joven y cercano, útil para interpretar el color y la edad de las estrellas y la nebulosidad de reflexión.",
  m57: "La Nebulosa del Anillo muestra una fase tardía de la evolución de las estrellas similares al Sol, con gas expulsado que rodea un remanente central caliente.",
};

/** Title and alternative text of each curated image. English is in ../../objectMedia.ts. */
export const CURATED_MEDIA_TEXT: Record<string, { title: string; alt: string }> = {
  sun: { title: "Vista del disco completo del Sol", alt: "Vista del disco completo del Sol obtenida por el Solar Dynamics Observatory." },
  mercury: { title: "Los secretos de Mercurio al descubierto", alt: "Vista de Mercurio en color realzado obtenida por la sonda MESSENGER." },
  venus: { title: "Venus: vista global centrada en los 90 grados de longitud este", alt: "Vista global de radar de Venus, simulada por computadora." },
  earth: { title: "Canica Azul 2012", alt: "Vista del disco completo de la Tierra desde el espacio, con océanos azules, nubes blancas y continentes visibles." },
  moon: { title: "La cara visible de la Luna vista por Clementine", alt: "Mosaico global de la cara visible de la Luna." },
  phobos: { title: "Fobos desde 6800 kilómetros", alt: "Vista en color de Fobos, luna de Marte, obtenida por el Mars Reconnaissance Orbiter." },
  deimos: { title: "Las lunas de Marte", alt: "Imagen de la NASA que muestra Fobos y Deimos, las lunas de Marte." },
  mars: { title: "Los volcanes de Tharsis y Valles Marineris", alt: "Vista global de Marte que muestra la región volcánica de Tharsis y el largo sistema de cañones de Valles Marineris." },
  jupiter: { title: "Globo de Júpiter en alta resolución", alt: "Globo de Júpiter en color, con nubes en bandas y la Gran Mancha Roja." },
  io: { title: "Coladas de lava activas en el volcán Prometheus de Ío", alt: "Vista en el infrarrojo cercano de la actividad volcánica de Ío obtenida por la sonda Galileo." },
  europa: { title: "Huellas de arcilla en Europa", alt: "Imagen de la NASA del terreno helado y fracturado de Europa." },
  ganymede: { title: "Vista estereoscópica de la región Galileo de Ganimedes", alt: "Vista del terreno surcado de Ganimedes obtenida por la sonda Galileo." },
  callisto: { title: "Vista global de Calisto en color", alt: "Imagen global en color de Calisto, luna de Júpiter." },
  saturn: { title: "A través de anillos resplandecientes", alt: "Vista de Saturno y del plano de sus anillos obtenida por la sonda Cassini." },
  enceladus: { title: "Encélado, la luna de los géiseres de Saturno", alt: "Vista de Encélado obtenida por la sonda Cassini, con terreno helado y brillante." },
  titan: { title: "Titán luminoso", alt: "Imagen de Titán obtenida por la sonda Cassini, con neblina atmosférica." },
  uranus: { title: "Urano visto por la Voyager 2", alt: "Imagen de Urano obtenida por la Voyager 2, en la que el planeta aparece como un disco verde azulado." },
  neptune: { title: "Neptuno desde la Voyager 2", alt: "Imagen de Neptuno obtenida por la Voyager 2, con formaciones atmosféricas azules." },
  pluto: { title: "Mosaicos globales de Plutón y Caronte", alt: "Mosaicos globales de Plutón y Caronte obtenidos por la sonda New Horizons." },
  m31: { title: "Vista panorámica en alta definición de la Galaxia de Andrómeda obtenida por el Hubble", alt: "Amplio mosaico de la Galaxia de Andrómeda obtenido por el Hubble, que muestra densos campos de estrellas y bandas de polvo." },
  m5: { title: "Messier 5", alt: "Imagen del cúmulo globular Messier 5 obtenida por el Hubble." },
  m11: { title: "M11: Cúmulo del Pato Salvaje", alt: "Imagen del cúmulo abierto del Pato Salvaje obtenida por el Hubble." },
  m13: { title: "M13: cúmulo globular", alt: "Imagen del denso cúmulo globular Messier 13 obtenida por el Hubble." },
  m42: { title: "Nebulosa de Orión y arco de choque", alt: "Vista del gas y el polvo brillantes de la Nebulosa de Orión obtenida por el Hubble." },
  m45: { title: "Las Siete Hermanas", alt: "Vista en infrarrojo del cúmulo estelar de las Pléyades y del polvo que lo rodea." },
  m44: { title: "Imagen de Messier 44 obtenida con la ACS", alt: "Vista a través de las regiones exteriores del Cúmulo del Pesebre obtenida por el Hubble." },
  m57: { title: "Una estrella condenada vista a través de un barril de gas", alt: "Imagen de la Nebulosa del Anillo obtenida por el Hubble, con gas brillante alrededor de una estrella central." },
};
