/** Curated object summaries, Spanish. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "El Sol es el ancla de todas las órbitas del Sistema Solar en el atlas y proporciona la escala de referencia para la masa, el radio y la luminosidad de las estrellas.",
  mercury: "Mercurio es el planeta más interior y muestra cómo el calentamiento solar y la historia de las mareas dan forma a los mundos rocosos pequeños.",
  venus: "Venus es casi un gemelo de la Tierra en tamaño, pero un extremo climático, lo que lo convierte en un punto de comparación clave para la evolución de los planetas terrestres.",
  earth: "La Tierra es la referencia de observación del atlas y el único mundo habitado conocido, y vincula la posición en el cielo con la distancia y la escala locales.",
  moon: "La Luna conserva una historia de impactos y volcanismo, y está lo bastante cerca como para conectar el detalle telescópico con la geología de la era de las naves espaciales.",
  mars: "Marte es el planeta rocoso cercano mejor estudiado aparte de la Tierra y una referencia para la pérdida del clima, el volcanismo y la exploración de la superficie.",
  jupiter: "Júpiter domina la dinámica del Sistema Solar, y sus lunas principales forman un conjunto compacto de comparación de mundos geológicamente diversos.",
  saturn: "Saturno reúne la estructura de los planetas gigantes, los anillos y los sistemas de lunas en uno de los laboratorios naturales más claros del Sistema Solar.",
  uranus: "Urano es un gigante de hielo con una inclinación axial extrema, útil para comparar los interiores de los planetas exteriores y la geometría estacional.",
  neptune: "Neptuno es el ancla de los planetas clásicos exteriores y muestra cómo una dinámica atmosférica rápida persiste lejos del Sol.",
  pluto: "Plutón conecta los planetas enanos, la historia del cinturón de Kuiper y la geología de volátiles en el borde del sistema planetario.",
  io: "Ío es la luna con más actividad volcánica del Sistema Solar, impulsada por el calentamiento de marea dentro del sistema de lunas de Júpiter.",
  europa: "Europa es un objetivo de gran valor entre los mundos oceánicos, porque su superficie helada probablemente cubre un océano global salado.",
  ganymede: "Ganimedes es la luna más grande del Sistema Solar y la única luna de la que se sabe que genera su propio campo magnético.",
  callisto: "Calisto registra impactos antiguos del Sistema Solar exterior y contrasta fuertemente con las lunas galileanas interiores, más activas.",
  titan: "Titán es la única luna con una atmósfera densa y líquidos estables en la superficie, lo que la hace central para la química planetaria comparada.",
  enceladus: "Encélado expulsa al espacio material de un océano subsuperficial, lo que lo convierte en uno de los objetivos más directos para tomar muestras de un mundo oceánico.",
  m13: "M13 es un cúmulo globular de referencia del cielo boreal y muestra una población estelar densa y antigua en el halo de la Vía Láctea.",
  m31: "Andrómeda es la galaxia espiral grande más cercana y sitúa la Vía Láctea en el contexto directo del Grupo Local.",
  m42: "La Nebulosa de Orión es una región cercana de formación de estrellas masivas, donde las estrellas jóvenes iluminan el gas y el polvo en los que nacieron.",
  m45: "Las Pléyades son un cúmulo abierto joven y cercano, útil para interpretar el color y la edad de las estrellas y la nebulosidad de reflexión.",
  m57: "La Nebulosa del Anillo muestra una fase tardía de la evolución de las estrellas similares al Sol, con gas expulsado que rodea un remanente central caliente.",
};
