/** Curated object summaries, French. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Le Soleil est le point d’ancrage de toutes les orbites du Système solaire dans l’atlas et fournit l’échelle de référence pour la masse, le rayon et la luminosité des étoiles.",
  mercury: "Mercure est la planète la plus interne et montre comment le chauffage solaire et l’histoire des effets de marée façonnent les petits mondes rocheux.",
  venus: "Vénus est presque la jumelle de la Terre par la taille, mais un extrême climatique, ce qui en fait un point de comparaison essentiel pour l’évolution des planètes telluriques.",
  earth: "La Terre est la référence d’observation de l’atlas et le seul monde habité connu, reliant la position dans le ciel à la distance et à l’échelle locales.",
  moon: "La Lune conserve une histoire d’impacts et de volcanisme, et elle est assez proche pour relier le détail télescopique à la géologie de l’ère des engins spatiaux.",
  mars: "Mars est, en dehors de la Terre, la planète rocheuse proche la mieux étudiée et une référence pour la perte du climat, le volcanisme et l’exploration de surface.",
  jupiter: "Jupiter domine la dynamique du Système solaire, et ses principales lunes forment un ensemble de comparaison compact de mondes géologiquement variés.",
  saturn: "Saturne réunit la structure des planètes géantes, les anneaux et les systèmes de lunes dans l’un des laboratoires naturels les plus clairs du Système solaire.",
  uranus: "Uranus est une géante de glaces à l’inclinaison axiale extrême, utile pour comparer l’intérieur des planètes externes et la géométrie saisonnière.",
  neptune: "Neptune est le point d’ancrage des planètes classiques externes et montre comment une dynamique atmosphérique rapide persiste loin du Soleil.",
  pluto: "Pluton relie les planètes naines, l’histoire de la ceinture de Kuiper et la géologie des volatils à la limite du système planétaire.",
  io: "Io est la lune à l’activité volcanique la plus intense du Système solaire, alimentée par le chauffage de marée au sein du système de lunes de Jupiter.",
  europa: "Europe est une cible de grande valeur parmi les mondes océaniques, car sa surface glacée recouvre probablement un océan global salé.",
  ganymede: "Ganymède est la plus grande lune du Système solaire et la seule lune connue pour générer son propre champ magnétique.",
  callisto: "Callisto garde la trace d’impacts anciens du Système solaire externe et contraste fortement avec les lunes galiléennes internes, plus actives.",
  titan: "Titan est la seule lune dotée d’une atmosphère dense et de liquides stables en surface, ce qui lui donne une place centrale en chimie planétaire comparée.",
  enceladus: "Encelade éjecte dans l’espace de la matière issue d’un océan souterrain, ce qui en fait l’une des cibles les plus directes pour l’échantillonnage d’un monde océanique.",
  m13: "M13 est un amas globulaire de référence du ciel boréal et montre une population stellaire dense et ancienne dans le halo de la Voie lactée.",
  m31: "Andromède est la grande galaxie spirale la plus proche et place la Voie lactée dans le contexte direct du Groupe local.",
  m42: "La nébuleuse d’Orion est une région proche de formation d’étoiles massives, où de jeunes étoiles illuminent le gaz et la poussière dont elles sont nées.",
  m45: "Les Pléiades sont un amas ouvert jeune et proche, utile pour lire la couleur et l’âge des étoiles ainsi que la nébulosité par réflexion.",
  m57: "La nébuleuse de l’Anneau montre une phase tardive de l’évolution des étoiles semblables au Soleil, avec du gaz expulsé qui entoure un résidu central chaud.",
};

/** Title and alternative text of each curated image. English is in ../../objectMedia.ts. */
export const CURATED_MEDIA_TEXT: Record<string, { title: string; alt: string }> = {
  sun: { title: "Vue du disque entier du Soleil", alt: "Vue du disque entier du Soleil prise par le Solar Dynamics Observatory." },
  mercury: { title: "Les secrets de Mercure dévoilés", alt: "Vue de Mercure en couleurs rehaussées, prise par MESSENGER." },
  venus: { title: "Vénus – vue globale centrée sur 90 degrés de longitude est", alt: "Vue radar globale de Vénus, simulée par ordinateur." },
  earth: { title: "La Bille bleue 2012", alt: "Vue du disque entier de la Terre depuis l’espace, avec des océans bleus, des nuages blancs et des continents visibles." },
  moon: { title: "La face visible de la Lune vue par Clementine", alt: "Mosaïque globale de la face visible de la Lune." },
  phobos: { title: "Phobos à 6 800 kilomètres de distance", alt: "Vue en couleurs de la lune martienne Phobos, prise par Mars Reconnaissance Orbiter." },
  deimos: { title: "Les lunes de Mars", alt: "Image de la NASA montrant les lunes martiennes Phobos et Déimos." },
  mars: { title: "Les volcans de Tharsis et Valles Marineris", alt: "Vue globale de Mars montrant la région volcanique de Tharsis et le long système de canyons de Valles Marineris." },
  jupiter: { title: "Globe de Jupiter en haute résolution", alt: "Globe en couleurs de Jupiter, avec ses bandes nuageuses et la Grande Tache rouge." },
  io: { title: "Coulées de lave actives du volcan Prométhée, sur Io", alt: "Vue de l’activité volcanique sur Io dans le proche infrarouge, prise par la sonde Galileo." },
  europa: { title: "Traces d’argile sur Europe", alt: "Image de la NASA du terrain glacé et fracturé d’Europe." },
  ganymede: { title: "Vue stéréoscopique de la région Galileo Regio sur Ganymède", alt: "Vue de terrains rainurés sur Ganymède, prise par la sonde Galileo." },
  callisto: { title: "Vue globale de Callisto en couleurs", alt: "Image globale en couleurs de Callisto, lune de Jupiter." },
  saturn: { title: "À travers les anneaux resplendissants", alt: "Vue de Saturne et du plan de ses anneaux, prise par Cassini." },
  enceladus: { title: "Encelade, la lune à geysers de Saturne", alt: "Vue d’Encelade prise par Cassini, avec son terrain glacé et brillant." },
  titan: { title: "La lueur de Titan", alt: "Image de Titan prise par Cassini, avec sa brume atmosphérique." },
  uranus: { title: "Uranus vue par Voyager 2", alt: "Image de Voyager 2 montrant Uranus sous la forme d’un disque bleu-vert." },
  neptune: { title: "Neptune vue par Voyager 2", alt: "Image de Neptune prise par Voyager 2, avec des structures atmosphériques bleues." },
  pluto: { title: "Mosaïques globales de Pluton et de Charon", alt: "Mosaïques globales de Pluton et de Charon réalisées par New Horizons." },
  m31: { title: "Vue panoramique en haute définition de la galaxie d’Andromède par Hubble", alt: "Grande mosaïque de la galaxie d’Andromède réalisée par Hubble, montrant des champs d’étoiles denses et des bandes de poussière." },
  m5: { title: "Messier 5", alt: "Image de l’amas globulaire Messier 5 prise par Hubble." },
  m11: { title: "M11 – amas du Canard sauvage", alt: "Image de l’amas ouvert du Canard sauvage prise par Hubble." },
  m13: { title: "M13 – amas globulaire", alt: "Image de l’amas globulaire dense Messier 13 prise par Hubble." },
  m42: { title: "Nébuleuse d’Orion et arc de choc", alt: "Vue par Hubble du gaz et de la poussière qui brillent dans la nébuleuse d’Orion." },
  m45: { title: "Les Sept Sœurs", alt: "Vue infrarouge de l’amas d’étoiles des Pléiades et de la poussière qui l’entoure." },
  m44: { title: "Image ACS de Messier 44", alt: "Vue par Hubble à travers la périphérie de l’amas de la Crèche." },
  m57: { title: "Une étoile condamnée vue au fond d’un tonneau de gaz", alt: "Image de la nébuleuse de l’Anneau prise par Hubble, avec du gaz lumineux autour d’une étoile centrale." },
};
