/** Curated object summaries, French. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Le Soleil est le point d’ancrage de toutes les orbites du Système solaire dans l’atlas et fournit l’échelle de référence pour la masse, le rayon et la luminosité des étoiles.",
  mercury: "Mercure est la planète la plus interne et montre comment le chauffage solaire et l’histoire des effets de marée façonnent les petits mondes rocheux.",
  venus: "Vénus est presque la jumelle de la Terre par la taille, mais un extrême climatique, ce qui en fait un point de comparaison essentiel pour l’évolution des planètes telluriques.",
  earth: "La Terre est la référence d’observation de l’atlas et le seul monde habité connu, reliant la position dans le ciel à la distance et à l’échelle locales.",
  moon: "La Lune conserve une histoire d’impacts et de volcanisme, et elle est assez proche pour relier le détail télescopique à la géologie de l’ère des engins spatiaux.",
  mars: "Mars est, en dehors de la Terre, la planète rocheuse proche la mieux étudiée et une référence pour la perte du climat, le volcanisme et l’exploration de surface.",
  jupiter: "Jupiter domine la dynamique du Système solaire, et ses principales lunes forment un ensemble de comparaison compact de mondes géologiquement variés.",
  saturn: "Saturne réunit la structure des planètes géantes, les anneaux et les systèmes de lunes dans l’un des laboratoires naturels les plus clairs du Système solaire.",
  uranus: "Uranus est une géante de glaces à l’inclinaison axiale extrême, utile pour comparer l’intérieur des planètes externes et la géométrie saisonnière.",
  neptune: "Neptune est le point d’ancrage des planètes classiques externes et montre comment une dynamique atmosphérique rapide persiste loin du Soleil.",
  pluto: "Pluton relie les planètes naines, l’histoire de la ceinture de Kuiper et la géologie des volatils à la limite du système planétaire.",
  io: "Io est la lune à l’activité volcanique la plus intense du Système solaire, alimentée par le chauffage de marée au sein du système de lunes de Jupiter.",
  europa: "Europe est une cible de grande valeur parmi les mondes océaniques, car sa surface glacée recouvre probablement un océan global salé.",
  ganymede: "Ganymède est la plus grande lune du Système solaire et la seule lune connue pour générer son propre champ magnétique.",
  callisto: "Callisto garde la trace d’impacts anciens du Système solaire externe et contraste fortement avec les lunes galiléennes internes, plus actives.",
  titan: "Titan est la seule lune dotée d’une atmosphère dense et de liquides stables en surface, ce qui lui donne une place centrale en chimie planétaire comparée.",
  enceladus: "Encelade éjecte dans l’espace de la matière issue d’un océan souterrain, ce qui en fait l’une des cibles les plus directes pour l’échantillonnage d’un monde océanique.",
  m13: "M13 est un amas globulaire de référence du ciel boréal et montre une population stellaire dense et ancienne dans le halo de la Voie lactée.",
  m31: "Andromède est la grande galaxie spirale la plus proche et place la Voie lactée dans le contexte direct du Groupe local.",
  m42: "La nébuleuse d’Orion est une région proche de formation d’étoiles massives, où de jeunes étoiles illuminent le gaz et la poussière dont elles sont nées.",
  m45: "Les Pléiades sont un amas ouvert jeune et proche, utile pour lire la couleur et l’âge des étoiles ainsi que la nébulosité par réflexion.",
  m57: "La nébuleuse de l’Anneau montre une phase tardive de l’évolution des étoiles semblables au Soleil, avec du gaz expulsé qui entoure un résidu central chaud.",
};
