/** Curated object summaries, Italian. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Il Sole è il punto di ancoraggio di tutte le orbite del Sistema solare nell’atlante e fornisce la scala di riferimento per la massa, il raggio e la luminosità delle stelle.",
  mercury: "Mercurio è il pianeta più interno e mostra come il riscaldamento solare e la storia mareale modellano i piccoli mondi rocciosi.",
  venus: "Venere è quasi un gemello della Terra per dimensioni, ma un estremo climatico, e questo ne fa un termine di confronto essenziale per l’evoluzione dei pianeti terrestri.",
  earth: "La Terra è il riferimento di osservazione dell’atlante e l’unico mondo abitato conosciuto, e lega la posizione nel cielo alla distanza e alla scala locali.",
  moon: "La Luna conserva la storia degli impatti e del vulcanismo ed è abbastanza vicina da collegare il dettaglio telescopico alla geologia dell’era dei veicoli spaziali.",
  mars: "Marte è, oltre alla Terra, il pianeta roccioso vicino meglio studiato e un riferimento per la perdita del clima, il vulcanismo e l’esplorazione della superficie.",
  jupiter: "Giove domina la dinamica del Sistema solare, e le sue lune principali formano un insieme compatto di confronto di mondi geologicamente diversi.",
  saturn: "Saturno unisce la struttura dei pianeti giganti, gli anelli e i sistemi di lune in uno dei laboratori naturali più chiari del Sistema solare.",
  uranus: "Urano è un gigante ghiacciato con un’inclinazione assiale estrema, utile per confrontare gli interni dei pianeti esterni e la geometria stagionale.",
  neptune: "Nettuno è il punto di ancoraggio dei pianeti classici esterni e mostra come una dinamica atmosferica rapida persiste lontano dal Sole.",
  pluto: "Plutone collega i pianeti nani, la storia della fascia di Kuiper e la geologia dei volatili al margine del sistema planetario.",
  io: "Io è la luna vulcanicamente più attiva del Sistema solare, alimentata dal riscaldamento mareale all’interno del sistema di lune di Giove.",
  europa: "Europa è un obiettivo di grande valore tra i mondi oceanici, perché la sua superficie ghiacciata copre probabilmente un oceano globale salato.",
  ganymede: "Ganimede è la luna più grande del Sistema solare e l’unica luna nota che genera un proprio campo magnetico.",
  callisto: "Callisto registra antichi impatti del Sistema solare esterno ed è in forte contrasto con le lune galileiane interne, più attive.",
  titan: "Titano è l’unica luna con un’atmosfera densa e liquidi stabili in superficie, e per questo è centrale per la chimica planetaria comparata.",
  enceladus: "Encelado espelle nello spazio materiale di un oceano sotto la superficie, e questo ne fa uno degli obiettivi più diretti per il campionamento di un mondo oceanico.",
  m13: "M13 è un ammasso globulare di riferimento del cielo boreale e mostra una popolazione stellare densa e antica nell’alone della Via Lattea.",
  m31: "Andromeda è la grande galassia a spirale più vicina e colloca la Via Lattea nel contesto diretto del Gruppo Locale.",
  m42: "La Nebulosa di Orione è una regione vicina di formazione di stelle massicce, dove stelle giovani illuminano il gas e la polvere da cui sono nate.",
  m45: "Le Pleiadi sono un ammasso aperto giovane e vicino, utile per leggere il colore e l’età delle stelle e la nebulosità a riflessione.",
  m57: "La Nebulosa Anello mostra una fase tarda dell’evoluzione delle stelle simili al Sole, con gas espulso che circonda un residuo centrale caldo.",
};
