/** Curated object summaries, Italian. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "Il Sole è il punto di ancoraggio di tutte le orbite del Sistema solare nell’atlante e fornisce la scala di riferimento per la massa, il raggio e la luminosità delle stelle.",
  mercury: "Mercurio è il pianeta più interno e mostra come il riscaldamento solare e la storia mareale modellano i piccoli mondi rocciosi.",
  venus: "Venere è quasi un gemello della Terra per dimensioni, ma un estremo climatico, e questo ne fa un termine di confronto essenziale per l’evoluzione dei pianeti terrestri.",
  earth: "La Terra è il riferimento di osservazione dell’atlante e l’unico mondo abitato conosciuto, e lega la posizione nel cielo alla distanza e alla scala locali.",
  moon: "La Luna conserva la storia degli impatti e del vulcanismo ed è abbastanza vicina da collegare il dettaglio telescopico alla geologia dell’era dei veicoli spaziali.",
  mars: "Marte è, oltre alla Terra, il pianeta roccioso vicino meglio studiato e un riferimento per la perdita del clima, il vulcanismo e l’esplorazione della superficie.",
  jupiter: "Giove domina la dinamica del Sistema solare, e le sue lune principali formano un insieme compatto di confronto di mondi geologicamente diversi.",
  saturn: "Saturno unisce la struttura dei pianeti giganti, gli anelli e i sistemi di lune in uno dei laboratori naturali più chiari del Sistema solare.",
  uranus: "Urano è un gigante ghiacciato con un’inclinazione assiale estrema, utile per confrontare gli interni dei pianeti esterni e la geometria stagionale.",
  neptune: "Nettuno è il punto di ancoraggio dei pianeti classici esterni e mostra come una dinamica atmosferica rapida persiste lontano dal Sole.",
  pluto: "Plutone collega i pianeti nani, la storia della fascia di Kuiper e la geologia dei volatili al margine del sistema planetario.",
  io: "Io è la luna vulcanicamente più attiva del Sistema solare, alimentata dal riscaldamento mareale all’interno del sistema di lune di Giove.",
  europa: "Europa è un obiettivo di grande valore tra i mondi oceanici, perché la sua superficie ghiacciata copre probabilmente un oceano globale salato.",
  ganymede: "Ganimede è la luna più grande del Sistema solare e l’unica luna nota che genera un proprio campo magnetico.",
  callisto: "Callisto registra antichi impatti del Sistema solare esterno ed è in forte contrasto con le lune galileiane interne, più attive.",
  titan: "Titano è l’unica luna con un’atmosfera densa e liquidi stabili in superficie, e per questo è centrale per la chimica planetaria comparata.",
  enceladus: "Encelado espelle nello spazio materiale di un oceano sotto la superficie, e questo ne fa uno degli obiettivi più diretti per il campionamento di un mondo oceanico.",
  m13: "M13 è un ammasso globulare di riferimento del cielo boreale e mostra una popolazione stellare densa e antica nell’alone della Via Lattea.",
  m31: "Andromeda è la grande galassia a spirale più vicina e colloca la Via Lattea nel contesto diretto del Gruppo Locale.",
  m42: "La Nebulosa di Orione è una regione vicina di formazione di stelle massicce, dove stelle giovani illuminano il gas e la polvere da cui sono nate.",
  m45: "Le Pleiadi sono un ammasso aperto giovane e vicino, utile per leggere il colore e l’età delle stelle e la nebulosità a riflessione.",
  m57: "La Nebulosa Anello mostra una fase tarda dell’evoluzione delle stelle simili al Sole, con gas espulso che circonda un residuo centrale caldo.",
};

/** Title and alternative text of each curated image. English is in ../../objectMedia.ts. */
export const CURATED_MEDIA_TEXT: Record<string, { title: string; alt: string }> = {
  sun: { title: "Vista del disco intero del Sole", alt: "Vista del disco intero del Sole ripresa dal Solar Dynamics Observatory." },
  mercury: { title: "I segreti di Mercurio svelati", alt: "Vista di Mercurio a colori accentuati ripresa da MESSENGER." },
  venus: { title: "Venere – vista globale centrata a 90 gradi di longitudine est", alt: "Vista radar globale di Venere simulata al computer." },
  earth: { title: "Biglia blu 2012", alt: "Vista del disco intero della Terra dallo spazio, con oceani blu, nuvole bianche e continenti visibili." },
  moon: { title: "La faccia visibile della Luna vista da Clementine", alt: "Mosaico globale della faccia visibile della Luna." },
  phobos: { title: "Fobos da 6800 chilometri di distanza", alt: "Vista a colori della luna marziana Fobos ripresa da Mars Reconnaissance Orbiter." },
  deimos: { title: "Le lune di Marte", alt: "Immagine NASA che mostra le lune marziane Fobos e Deimos." },
  mars: { title: "I vulcani di Tharsis e le Valles Marineris", alt: "Vista globale di Marte che mostra la regione vulcanica di Tharsis e il lungo sistema di canyon delle Valles Marineris." },
  jupiter: { title: "Globo di Giove ad alta risoluzione", alt: "Globo a colori di Giove con nubi a bande e la Grande Macchia Rossa." },
  io: { title: "Colate di lava attive presso il vulcano Prometheus, su Io", alt: "Vista nel vicino infrarosso dell’attività vulcanica su Io, ripresa dalla sonda Galileo." },
  europa: { title: "Tracce di argilla su Europa", alt: "Immagine NASA del terreno ghiacciato e fratturato di Europa." },
  ganymede: { title: "Vista stereoscopica della regione Galileo Regio su Ganimede", alt: "Vista di terreni solcati su Ganimede ripresa dalla sonda Galileo." },
  callisto: { title: "Vista globale di Callisto a colori", alt: "Immagine globale a colori di Callisto, luna di Giove." },
  saturn: { title: "Attraverso anelli risplendenti", alt: "Vista di Saturno e del piano dei suoi anelli ripresa da Cassini." },
  enceladus: { title: "Encelado, la luna dei geyser di Saturno", alt: "Vista di Encelado ripresa da Cassini, con terreno ghiacciato e brillante." },
  titan: { title: "Il bagliore di Titano", alt: "Immagine di Titano ripresa da Cassini, con foschia atmosferica." },
  uranus: { title: "Urano visto da Voyager 2", alt: "Immagine di Voyager 2 che mostra Urano come un disco blu-verde." },
  neptune: { title: "Nettuno visto da Voyager 2", alt: "Immagine di Nettuno ripresa da Voyager 2, con strutture atmosferiche blu." },
  pluto: { title: "Mosaici globali di Plutone e Caronte", alt: "Mosaici globali di Plutone e Caronte realizzati da New Horizons." },
  m31: { title: "Vista panoramica ad alta definizione della Galassia di Andromeda ripresa da Hubble", alt: "Ampio mosaico di Hubble della Galassia di Andromeda, che mostra densi campi stellari e bande di polvere." },
  m5: { title: "Messier 5", alt: "Immagine di Hubble dell’ammasso globulare Messier 5." },
  m11: { title: "M11 – Ammasso dell’Anitra Selvatica", alt: "Immagine di Hubble dell’ammasso aperto dell’Anitra Selvatica." },
  m13: { title: "M13 – ammasso globulare", alt: "Immagine di Hubble del denso ammasso globulare Messier 13." },
  m42: { title: "Nebulosa di Orione e onda d’urto ad arco", alt: "Vista di Hubble del gas e delle polveri che brillano nella Nebulosa di Orione." },
  m45: { title: "Le Sette Sorelle", alt: "Vista nell’infrarosso dell’ammasso stellare delle Pleiadi e della polvere circostante." },
  m44: { title: "Immagine ACS di Messier 44", alt: "Vista di Hubble attraverso la periferia dell’Ammasso del Presepe." },
  m57: { title: "Una stella condannata vista in fondo a un barile di gas", alt: "Immagine di Hubble della Nebulosa Anello, con gas luminoso attorno a una stella centrale." },
};
