/** Curated object summaries, Brazilian Portuguese. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "O Sol ancora todas as órbitas do Sistema Solar no atlas e fornece a escala de referência para a massa, o raio e a luminosidade das estrelas.",
  mercury: "Mercúrio é o planeta mais interno e mostra como o aquecimento solar e a história das marés moldam os pequenos mundos rochosos.",
  venus: "Vênus é quase um gêmeo da Terra em tamanho, mas um extremo climático, o que faz dele um ponto de comparação fundamental para a evolução dos planetas terrestres.",
  earth: "A Terra é a referência de observação do atlas e o único mundo habitado conhecido, ligando a posição no céu à distância e à escala locais.",
  moon: "A Lua preserva a história de impactos e de vulcanismo e está perto o bastante para ligar os detalhes telescópicos à geologia da era das naves espaciais.",
  mars: "Marte é o planeta rochoso próximo mais bem estudado além da Terra e uma referência para a perda do clima, o vulcanismo e a exploração da superfície.",
  jupiter: "Júpiter domina a dinâmica do Sistema Solar, e suas luas principais formam um conjunto compacto de comparação de mundos geologicamente diversos.",
  saturn: "Saturno reúne a estrutura dos planetas gigantes, os anéis e os sistemas de luas em um dos laboratórios naturais mais claros do Sistema Solar.",
  uranus: "Urano é um gigante de gelo com uma inclinação axial extrema, útil para comparar o interior dos planetas exteriores e a geometria sazonal.",
  neptune: "Netuno ancora os planetas clássicos exteriores e mostra como uma dinâmica atmosférica rápida persiste longe do Sol.",
  pluto: "Plutão liga os planetas anões, a história do Cinturão de Kuiper e a geologia de voláteis na borda do sistema planetário.",
  io: "Io é a lua com maior atividade vulcânica do Sistema Solar, impulsionada pelo aquecimento de maré dentro do sistema de luas de Júpiter.",
  europa: "Europa é um alvo de grande valor entre os mundos oceânicos, porque sua superfície gelada provavelmente recobre um oceano global salgado.",
  ganymede: "Ganimedes é a maior lua do Sistema Solar e a única lua conhecida que gera seu próprio campo magnético.",
  callisto: "Calisto registra impactos antigos do Sistema Solar exterior e contrasta fortemente com as luas galileanas interiores, mais ativas.",
  titan: "Titã é a única lua com atmosfera densa e líquidos estáveis na superfície, o que a torna central para a química planetária comparada.",
  enceladus: "Encélado expele para o espaço material de um oceano subsuperficial, o que faz dele um dos alvos mais diretos para a amostragem de um mundo oceânico.",
  m13: "M13 é um aglomerado globular de referência do céu boreal e mostra uma população estelar densa e antiga no halo da Via Láctea.",
  m31: "Andrômeda é a grande galáxia espiral mais próxima e coloca a Via Láctea no contexto direto do Grupo Local.",
  m42: "A Nebulosa de Órion é uma região próxima de formação de estrelas massivas, onde estrelas jovens iluminam o gás e a poeira em que nasceram.",
  m45: "As Plêiades são um aglomerado aberto jovem e próximo, útil para interpretar a cor e a idade das estrelas e a nebulosidade de reflexão.",
  m57: "A Nebulosa do Anel mostra uma fase tardia da evolução das estrelas semelhantes ao Sol, com gás expelido ao redor de um remanescente central quente.",
};

/** Title and alternative text of each curated image. English is in ../../objectMedia.ts. */
export const CURATED_MEDIA_TEXT: Record<string, { title: string; alt: string }> = {
  sun: { title: "Vista do disco completo do Sol", alt: "Vista do disco completo do Sol obtida pelo Solar Dynamics Observatory." },
  mercury: { title: "Desvendando os segredos de Mercúrio", alt: "Vista de Mercúrio em cores realçadas obtida pela sonda MESSENGER." },
  venus: { title: "Vênus: vista global centrada em 90 graus de longitude leste", alt: "Vista global de radar de Vênus, simulada por computador." },
  earth: { title: "Bolinha de Gude Azul 2012", alt: "Vista do disco completo da Terra a partir do espaço, com oceanos azuis, nuvens brancas e continentes visíveis." },
  moon: { title: "O lado visível da Lua visto pela Clementine", alt: "Mosaico global do lado visível da Lua." },
  phobos: { title: "Fobos a 6.800 quilômetros de distância", alt: "Vista em cores de Fobos, lua de Marte, obtida pela sonda Mars Reconnaissance Orbiter." },
  deimos: { title: "As luas de Marte", alt: "Imagem da NASA que mostra Fobos e Deimos, as luas de Marte." },
  mars: { title: "Os vulcões de Tharsis e Valles Marineris", alt: "Vista global de Marte que mostra a região vulcânica de Tharsis e o longo sistema de cânions de Valles Marineris." },
  jupiter: { title: "Globo de Júpiter em alta resolução", alt: "Globo de Júpiter em cores, com nuvens em faixas e a Grande Mancha Vermelha." },
  io: { title: "Fluxos de lava ativos no vulcão Prometheus, em Io", alt: "Vista no infravermelho próximo da atividade vulcânica em Io, obtida pela sonda Galileo." },
  europa: { title: "Marcas de argila em Europa", alt: "Imagem da NASA do terreno gelado e fraturado de Europa." },
  ganymede: { title: "Vista estereoscópica da região Galileo de Ganimedes", alt: "Vista do terreno sulcado de Ganimedes obtida pela sonda Galileo." },
  callisto: { title: "Vista global de Calisto em cores", alt: "Imagem global em cores de Calisto, lua de Júpiter." },
  saturn: { title: "Através de anéis resplandecentes", alt: "Vista de Saturno e do plano de seus anéis obtida pela sonda Cassini." },
  enceladus: { title: "Encélado, a lua dos gêiseres de Saturno", alt: "Vista de Encélado obtida pela sonda Cassini, com terreno gelado e brilhante." },
  titan: { title: "Titã reluzente", alt: "Imagem de Titã obtida pela sonda Cassini, com névoa atmosférica." },
  uranus: { title: "Urano visto pela Voyager 2", alt: "Imagem de Urano obtida pela Voyager 2, na qual o planeta aparece como um disco azul-esverdeado." },
  neptune: { title: "Netuno a partir da Voyager 2", alt: "Imagem de Netuno obtida pela Voyager 2, com feições atmosféricas azuis." },
  pluto: { title: "Mosaicos globais de Plutão e Caronte", alt: "Mosaicos globais de Plutão e Caronte obtidos pela sonda New Horizons." },
  m31: { title: "Vista panorâmica em alta definição da Galáxia de Andrômeda obtida pelo Hubble", alt: "Amplo mosaico da Galáxia de Andrômeda obtido pelo Hubble, que mostra campos densos de estrelas e faixas de poeira." },
  m5: { title: "Messier 5", alt: "Imagem do aglomerado globular Messier 5 obtida pelo Hubble." },
  m11: { title: "M11: Aglomerado do Pato Selvagem", alt: "Imagem do aglomerado aberto do Pato Selvagem obtida pelo Hubble." },
  m13: { title: "M13: aglomerado globular", alt: "Imagem do denso aglomerado globular Messier 13 obtida pelo Hubble." },
  m42: { title: "Nebulosa de Órion e choque em arco", alt: "Vista do gás e da poeira brilhantes da Nebulosa de Órion obtida pelo Hubble." },
  m45: { title: "As Sete Irmãs", alt: "Vista em infravermelho do aglomerado estelar das Plêiades e da poeira ao redor." },
  m44: { title: "Imagem de Messier 44 obtida com a ACS", alt: "Vista através das regiões externas do Aglomerado da Colmeia obtida pelo Hubble." },
  m57: { title: "Uma estrela condenada vista através de um barril de gás", alt: "Imagem da Nebulosa do Anel obtida pelo Hubble, com gás brilhante ao redor de uma estrela central." },
};
