/** Curated object summaries, Brazilian Portuguese. English is in ../curatedObjectSummaries.ts. */
export const CURATED_OBJECT_SUMMARIES: Record<string, string> = {
  sun: "O Sol ancora todas as órbitas do Sistema Solar no atlas e fornece a escala de referência para a massa, o raio e a luminosidade das estrelas.",
  mercury: "Mercúrio é o planeta mais interno e mostra como o aquecimento solar e a história das marés moldam os pequenos mundos rochosos.",
  venus: "Vênus é quase um gêmeo da Terra em tamanho, mas um extremo climático, o que faz dele um ponto de comparação fundamental para a evolução dos planetas terrestres.",
  earth: "A Terra é a referência de observação do atlas e o único mundo habitado conhecido, ligando a posição no céu à distância e à escala locais.",
  moon: "A Lua preserva a história de impactos e de vulcanismo e está perto o bastante para ligar os detalhes telescópicos à geologia da era das naves espaciais.",
  mars: "Marte é o planeta rochoso próximo mais bem estudado além da Terra e uma referência para a perda do clima, o vulcanismo e a exploração da superfície.",
  jupiter: "Júpiter domina a dinâmica do Sistema Solar, e suas luas principais formam um conjunto compacto de comparação de mundos geologicamente diversos.",
  saturn: "Saturno reúne a estrutura dos planetas gigantes, os anéis e os sistemas de luas em um dos laboratórios naturais mais claros do Sistema Solar.",
  uranus: "Urano é um gigante de gelo com uma inclinação axial extrema, útil para comparar o interior dos planetas exteriores e a geometria sazonal.",
  neptune: "Netuno ancora os planetas clássicos exteriores e mostra como uma dinâmica atmosférica rápida persiste longe do Sol.",
  pluto: "Plutão liga os planetas anões, a história do Cinturão de Kuiper e a geologia de voláteis na borda do sistema planetário.",
  io: "Io é a lua com maior atividade vulcânica do Sistema Solar, impulsionada pelo aquecimento de maré dentro do sistema de luas de Júpiter.",
  europa: "Europa é um alvo de grande valor entre os mundos oceânicos, porque sua superfície gelada provavelmente recobre um oceano global salgado.",
  ganymede: "Ganimedes é a maior lua do Sistema Solar e a única lua conhecida que gera seu próprio campo magnético.",
  callisto: "Calisto registra impactos antigos do Sistema Solar exterior e contrasta fortemente com as luas galileanas interiores, mais ativas.",
  titan: "Titã é a única lua com atmosfera densa e líquidos estáveis na superfície, o que a torna central para a química planetária comparada.",
  enceladus: "Encélado expele para o espaço material de um oceano subsuperficial, o que faz dele um dos alvos mais diretos para a amostragem de um mundo oceânico.",
  m13: "M13 é um aglomerado globular de referência do céu boreal e mostra uma população estelar densa e antiga no halo da Via Láctea.",
  m31: "Andrômeda é a grande galáxia espiral mais próxima e coloca a Via Láctea no contexto direto do Grupo Local.",
  m42: "A Nebulosa de Órion é uma região próxima de formação de estrelas massivas, onde estrelas jovens iluminam o gás e a poeira em que nasceram.",
  m45: "As Plêiades são um aglomerado aberto jovem e próximo, útil para interpretar a cor e a idade das estrelas e a nebulosidade de reflexão.",
  m57: "A Nebulosa do Anel mostra uma fase tardia da evolução das estrelas semelhantes ao Sol, com gás expelido ao redor de um remanescente central quente.",
};
