import { decodeViewState, type ViewState } from "./viewState";
export type TourStep = { viewState: string; title: string; body: string; holdMs?: number };
export type Tour = { slug: string; title: string; description: string; steps: TourStep[] };
export type TourPlayerAdapter = { navigate(state: ViewState, options: { animate: boolean; slug: string; step: number; restoring: boolean; signal: AbortSignal }): Promise<void>; prewarm(state: ViewState): void; track(event: "tour_started" | "tour_completed", properties: Record<string, string>): void };
export class TourPlayer {
  private tour: Tour | null = null; private index = 0; private timer: number | null = null; private transition: AbortController | null = null; private plate = document.createElement("section");
  constructor(private adapter: TourPlayerAdapter) {
    Object.assign(this.plate, { id: "tour-player", className: "tour-player", hidden: true }); this.plate.setAttribute("aria-label", "Guided tour"); this.plate.setAttribute("aria-live", "polite"); document.querySelector("#app")?.append(this.plate);
    this.plate.addEventListener("click", (event) => { const target = event.target as HTMLElement; const action = target.closest<HTMLButtonElement>("[data-tour-action]")?.dataset.tourAction; if (action === "next") void this.go(this.index + 1); if (action === "previous") void this.go(this.index - 1); if (action === "close") this.close(); const dot = target.closest<HTMLButtonElement>("[data-tour-step]"); if (dot) void this.go(Number(dot.dataset.tourStep)); });
    window.addEventListener("keydown", (event) => { if (this.plate.hidden || event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (event.key === "ArrowRight") { event.preventDefault(); void this.go(this.index + 1); } if (event.key === "ArrowLeft") { event.preventDefault(); void this.go(this.index - 1); } if (event.key === "Escape") this.close(); });
  }
  async start(slug: string, step = 0) {
    const transition = this.beginTransition();
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return this.error("This tour address is invalid."); this.plate.hidden = false; this.plate.innerHTML = `<p role="status">Loading guided tour…</p>`;
    try { const response = await fetch(`/tours/${encodeURIComponent(slug)}.json`, { signal: transition.signal }); if (!response.ok) throw new Error("Tour unavailable"); const tour = await response.json() as Tour; if (transition.signal.aborted) return; if (tour.slug !== slug || !Array.isArray(tour.steps) || !tour.steps.length || tour.steps.some((item) => !decodeViewState(item.viewState))) throw new Error("Tour data is invalid"); this.tour = tour; this.adapter.track("tour_started", { tour: slug }); await this.go(Math.min(Math.max(step, 0), tour.steps.length - 1), true); if (!this.transition?.signal.aborted) this.plate.querySelector<HTMLButtonElement>("[data-tour-action='next']")?.focus(); } catch (error) { if (!transition.signal.aborted) this.error(error instanceof Error ? error.message : "Tour unavailable"); }
  }
  async restoreStep(step: number) { if (this.tour) await this.go(step, true); }
  private async go(index: number, restoring = false) {
    if (!this.tour || index < 0 || index >= this.tour.steps.length) return; const transition = this.beginTransition(); if (this.timer !== null) clearTimeout(this.timer); this.timer = null; this.index = index; const step = this.tour.steps[index]!; const state = decodeViewState(step.viewState)!; const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; this.plate.dataset.motion = reduced ? "cut" : "flight"; if (restoring) this.render(); await this.adapter.navigate(state, { animate: !reduced, slug: this.tour.slug, step: index, restoring, signal: transition.signal }); if (transition.signal.aborted) return; if (!restoring) this.render(); const next = this.tour.steps[index + 1]; if (next) this.adapter.prewarm(decodeViewState(next.viewState)!); if (!restoring && step.holdMs && next) this.timer = window.setTimeout(() => void this.go(index + 1), step.holdMs); if (index === this.tour.steps.length - 1) this.adapter.track("tour_completed", { tour: this.tour.slug });
  }
  private beginTransition() { this.transition?.abort(); this.transition = new AbortController(); return this.transition; }
  private render() { const tour = this.tour!, step = tour.steps[this.index]!; const dots = tour.steps.map((_, i) => `<button type="button" data-tour-step="${i}" aria-label="Go to step ${i + 1}" aria-current="${i === this.index ? "step" : "false"}"></button>`).join(""); this.plate.innerHTML = `<div class="tour-player__head"><p>${escapeHtml(tour.title)}</p><button type="button" data-tour-action="close" aria-label="Close guided tour">Close</button></div><p class="tour-player__progress">Step ${this.index + 1} of ${tour.steps.length}</p><h2 tabindex="-1">${escapeHtml(step.title)}</h2><p>${escapeHtml(step.body)}</p><div class="tour-player__dots" aria-label="Tour progress">${dots}</div><div class="tour-player__actions"><button type="button" data-tour-action="previous" ${this.index === 0 ? "disabled" : ""}>Previous</button><button type="button" data-tour-action="next" ${this.index === tour.steps.length - 1 ? "disabled" : ""}>Next</button></div>`; }
  private error(message: string) { this.plate.hidden = false; this.plate.innerHTML = `<p role="alert">${escapeHtml(message)}</p><button type="button" data-tour-action="close">Close</button>`; }
  close() { this.transition?.abort(); this.transition = null; if (this.timer !== null) clearTimeout(this.timer); this.timer = null; this.plate.hidden = true; }
}
function escapeHtml(value: string) { const span = document.createElement("span"); span.textContent = value; return span.innerHTML; }
